# Generated by Django 5.1.5 on 2026-01-17 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_return_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected annual return percentage for SRT investors', max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='investment_duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Investment duration in months'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='maximum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum SRT tokens per investment (optional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum SRT tokens per investment', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='srt_amount_raised',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total SRT tokens invested in this project', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='srt_enabled',
            field=models.BooleanField(default=False, help_text='Enable SRT token investments for this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='srt_funding_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SRT token funding goal', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea Stage'), ('seed', 'Seed Stage'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('expansion', 'Expansion Stage')], default='idea', max_length=20),
        ),
    ]
