# Generated by Django 5.1.5 on 2026-02-08 18:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_payment_attempt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, help_text='Business or company name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equity_offered',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of equity offered to investors', max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='financing_type',
            field=models.CharField(blank=True, choices=[('equity', 'Equity Financing'), ('debt', 'Debt Financing')], help_text='Type of investment financing', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate for debt financing (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='listing_type',
            field=models.CharField(choices=[('project', 'Project (Donations)'), ('venture', 'Venture (Investments)')], default='project', help_text='Project for donations, Venture for investments', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='repayment_period_months',
            field=models.PositiveIntegerField(default=0, help_text='Repayment period in months (for debt financing)'),
        ),
        migrations.AddField(
            model_name='project',
            name='use_of_funds',
            field=models.TextField(blank=True, help_text='How the investment funds will be used', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current company/venture valuation in USD', max_digits=15),
        ),
    ]
