# Generated by Django 5.1.5 on 2026-03-23 05:23

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.filter(slug__isnull=True):
        base_slug = slugify(project.title) or f"project-{project.id}"
        slug = base_slug
        counter = 1
        while Project.objects.filter(slug=slug).exclude(pk=project.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        project.slug = slug
        project.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_company_name_project_equity_offered_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
