# Generated by Django 5.1.5 on 2026-01-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text="Current balance of the partner's capital account in NGN", max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_account', to='accounts.partnerprofile')),
            ],
            options={
                'verbose_name': 'Partner Capital Account',
                'verbose_name_plural': 'Partner Capital Accounts',
            },
        ),
    ]
