# Generated by Django 5.1.5 on 2026-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_partnercapitalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_srt_partner',
            field=models.BooleanField(default=False, help_text='User has SRT Partner capabilities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='srt_partner_since',
            field=models.DateTimeField(blank=True, help_text='Date when user became an SRT partner', null=True),
        ),
    ]
