# Generated by Django 5.1.5 on 2026-01-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_srt_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_images/'),
        ),
    ]
