# Generated by Django 5.1.5 on 2026-02-06 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the donor', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donor_images/')),
                ('is_anonymous_by_default', models.BooleanField(default=False, help_text='If enabled, donations will be anonymous by default')),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, help_text='Total amount donated across all projects', max_digits=12)),
                ('projects_supported', models.PositiveIntegerField(default=0, help_text='Number of projects this donor has supported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Profile',
                'verbose_name_plural': 'Donor Profiles',
            },
        ),
    ]
