# Generated by Django 5.1.5 on 2026-01-15 07:26

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('style', models.CharField(choices=[('info', 'Info (Blue)'), ('alert', 'Alert (Red)'), ('success', 'Success (Green)')], default='info', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncubatorAcceleratorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='accelerator/')),
                ('application_info', ckeditor.fields.RichTextField(help_text='Information about the call for applications, eligibility, timeline, etc.')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_accepting_applications', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Incubator/Accelerator Page Content',
            },
        ),
        migrations.CreateModel(
            name='IncubatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=200)),
                ('applicant_name', models.CharField(default='', max_length=200)),
                ('applicant_email', models.EmailField(default='', max_length=254)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=20)),
                ('applicant_company', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='www.website.com')),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'Minimum Viable Product'), ('launched', 'Launched'), ('growing', 'Growing/Scaling')], default='idea', max_length=50)),
                ('industry', models.CharField(default='', help_text='e.g. FinTech, AgriTech, HealthTech', max_length=100)),
                ('application_text', ckeditor.fields.RichTextField(blank=True, default='', help_text='Describe your startup and what problem it solves')),
                ('traction', ckeditor.fields.RichTextField(blank=True, default='', help_text='Mention any traction, pilot users, revenue, etc.')),
                ('team_background', ckeditor.fields.RichTextField(blank=True, default='', help_text="Tell us about your team and why you're the right people to build this")),
                ('goals_for_program', models.TextField(blank=True, default='', help_text='What do you hope to achieve during the accelerator?')),
                ('funding_raised', models.CharField(blank=True, default='', help_text='e.g. $10,000 in grants, $5,000 from friends & family', max_length=100)),
                ('funding_needed', models.CharField(blank=True, default='', help_text='How much are you looking to raise post-program?', max_length=100)),
                ('pitch_deck', models.FileField(blank=True, default='', help_text='Upload your pitch deck (PDF, max 10MB)', upload_to='pitch_decks/')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StartUpRipples', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/favicon/')),
                ('primary_color', models.CharField(default='#28a745', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email for the team member', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Indicate if the team member is currently active')),
                ('is_visible', models.BooleanField(default=True, help_text='Indicate if the team member should be visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#28a745', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_investment_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about approval/rejection', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('funding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.fundingtype')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_offered', models.DecimalField(decimal_places=2, help_text='Percentage of equity offered', max_digits=5)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_investment', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment amount allowed (optional)', max_digits=10, null=True)),
                ('valuation', models.DecimalField(decimal_places=2, help_text='Project valuation in USD', max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_terms', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('actual_return', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_counted', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.investmentterm')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pledged_at', models.DateTimeField(auto_now_add=True)),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.reward')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='projects.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(help_text='HTML content')),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_sections', to='projects.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='projects.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('core_values', ckeditor.fields.RichTextField()),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('about_video', models.FileField(blank=True, upload_to='about/videos/')),
                ('about_video_thumbnail', models.ImageField(blank=True, upload_to='about/thumbnails/')),
                ('about_video_description', models.TextField(blank=True)),
                ('about_video_url', models.URLField(blank=True)),
                ('about_video_embed_code', models.TextField(blank=True, help_text='Embed code for the video, e.g., from YouTube')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team_members', models.ManyToManyField(blank=True, to='projects.teammember')),
            ],
            options={
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
        ),
    ]
