# Generated by Django 5.1.5 on 2025-02-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='current_amount',
            new_name='amount_raised',
        ),
    ]
