# Generated by Django 5.1.5 on 2025-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_current_amount_project_amount_raised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='goal',
            new_name='funding_goal',
        ),
    ]
