# Generated by Django 5.1.5 on 2025-02-21 22:25

from django.db import migrations


def create_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('projects', 'SiteSettings')
    SiteSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_sitesettings_options'),
    ]

    operations = [
        migrations.RunPython(create_site_settings),
    ]
