# Generated by Django 5.1.5 on 2025-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_heroslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='actual_return',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
