# Generated by Django 5.1.5 on 2025-02-22 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_investment_actual_return_alter_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
