# Generated by Django 5.1.5 on 2025-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_founderprofile_image_alter_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
