# Generated by Django 5.1.5 on 2025-04-21 10:32

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_investment_is_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentterm',
            name='maximum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment amount allowed (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
