# Generated by Django 5.1.5 on 2025-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_investmentterm_maximum_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='founder_cvs/'),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
