# Generated by Django 5.1.5 on 2025-04-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_customuser_address_line1_customuser_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='equity_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
