# Generated by Django 5.1.5 on 2025-04-22 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_location_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
