# Generated by Django 5.1.5 on 2025-04-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_testimonial_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
