# Generated by Django 5.1.5 on 2025-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin about approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
