# Generated by Django 5.1.5 on 2025-06-18 10:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_admin_notes_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncubatorAcceleratorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_description', ckeditor.fields.RichTextField()),
                ('application_info', ckeditor.fields.RichTextField(help_text='Information about the call for applications, eligibility, timeline, etc.')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_accepting_applications', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Incubator/Accelerator Page Content',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email for the team member', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Indicate if the team member is currently active')),
                ('is_visible', models.BooleanField(default=True, help_text='Indicate if the team member should be visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('', 'Select User Type'), ('founder', 'Founder'), ('donor', 'Donor/Pledger'), ('investor', 'Investor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='StartUpRipples', max_length=100),
        ),
        migrations.CreateModel(
            name='IncubatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=20)),
                ('applicant_company', models.CharField(blank=True, max_length=200)),
                ('application_text', models.TextField(blank=True, help_text='Additional information about the application')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubator_applications', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('core_values', models.TextField()),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('about_video', models.FileField(blank=True, upload_to='about/videos/')),
                ('about_video_thumbnail', models.ImageField(blank=True, upload_to='about/thumbnails/')),
                ('about_video_description', models.TextField(blank=True)),
                ('about_video_url', models.URLField(blank=True)),
                ('about_video_embed_code', models.TextField(blank=True, help_text='Embed code for the video, e.g., from YouTube')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team_members', models.ManyToManyField(blank=True, to='projects.teammember')),
            ],
            options={
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
