# Generated by Django 5.1.5 on 2025-06-18 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_contact_incubatoracceleratorpage_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='core_values',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
