# Generated by Django 5.1.5 on 2025-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_aboutpage_core_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='accelerator/'),
        ),
    ]
