# Generated by Django 5.1.5 on 2025-06-18 20:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_incubatoracceleratorpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatorapplication',
            name='funding_needed',
            field=models.CharField(blank=True, default='', help_text='How much are you looking to raise post-program?', max_length=100),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='funding_raised',
            field=models.CharField(blank=True, default='', help_text='e.g. $10,000 in grants, $5,000 from friends & family', max_length=100),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='goals_for_program',
            field=models.TextField(blank=True, default='', help_text='What do you hope to achieve during the accelerator?'),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='industry',
            field=models.CharField(default='', help_text='e.g. FinTech, AgriTech, HealthTech', max_length=100),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='pitch_deck',
            field=models.FileField(blank=True, default='', help_text='Upload your pitch deck (PDF, max 10MB)', upload_to='pitch_decks/'),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='stage',
            field=models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'Minimum Viable Product'), ('launched', 'Launched'), ('growing', 'Growing/Scaling')], default='idea', max_length=50),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='team_background',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text="Tell us about your team and why you're the right people to build this"),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='traction',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Mention any traction, pilot users, revenue, etc.'),
        ),
        migrations.AddField(
            model_name='incubatorapplication',
            name='website',
            field=models.URLField(blank=True, default='www.website.com'),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='applicant_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='applicant_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='application_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Describe your startup and what problem it solves'),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='project',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incubatorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
    ]
