# Generated by Django 5.1.5 on 2025-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_incubatorapplication_funding_needed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
