# Generated by Django 5.1.5 on 2026-03-08 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_ngn',
            field=models.PositiveIntegerField(default=0, help_text='Amount in NGN kobo units (amount * 1600)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='actual_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Awaiting Payment'), ('pending_approval', 'Pending Founder Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('completed', 'Completed'), ('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.investmentterm'),
        ),
        migrations.CreateModel(
            name='InvestorEscrowBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
