# Generated by Django 5.1.5 on 2026-04-02 05:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_investment_payment_fields'),
        ('projects', '0006_backfill_project_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount requested in USD', max_digits=12)),
                ('amount_ngn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Equivalent amount in NGN (amount_usd * rate)', max_digits=15)),
                ('bank_name', models.CharField(help_text='Recipient bank name', max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from founder')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_founder_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The venture project funds are being withdrawn from', on_delete=django.db.models.deletion.CASCADE, related_name='founder_withdrawals', to='projects.project')),
            ],
            options={
                'verbose_name': 'Founder Withdrawal Request',
                'verbose_name_plural': 'Founder Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
