# Generated by Django 5.1.5 on 2026-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_founder_withdrawal_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderwithdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Paystack bank code e.g. 058 for GTBank', max_length=20),
        ),
        migrations.AddField(
            model_name='founderwithdrawalrequest',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=100),
        ),
        migrations.AddField(
            model_name='founderwithdrawalrequest',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, help_text='Paystack transfer code', max_length=100),
        ),
        migrations.AddField(
            model_name='founderwithdrawalrequest',
            name='transfer_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
