# Generated by Django 5.1.5 on 2026-01-15 11:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokens', models.PositiveIntegerField(help_text='Number of SRT tokens in this package')),
                ('price_ngn', models.DecimalField(decimal_places=2, help_text='Price in NGN', max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('bonus_tokens', models.PositiveIntegerField(default=0, help_text='Bonus tokens included')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Package',
                'verbose_name_plural': 'Token Packages',
                'ordering': ['order', 'price_ngn'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_tokens_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_tokens_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_tokens_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tokens earned from returns, bonuses, referrals', max_digits=15)),
                ('total_investment_value_ngn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total NGN value of all investments', max_digits=15)),
                ('locked_tokens', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tokens locked in active investments', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Capital Account',
                'verbose_name_plural': 'Partner Capital Accounts',
            },
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonus_tokens', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='srt.partnercapitalaccount')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srt.tokenpackage')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Purchase',
                'verbose_name_plural': 'Token Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ventures/')),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Funding goal in SRT tokens', max_digits=15)),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum SRT tokens per investment', max_digits=12)),
                ('maximum_investment', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum SRT tokens per investment (optional)', max_digits=12, null=True)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return percentage', max_digits=5)),
                ('investment_duration_months', models.PositiveIntegerField(help_text='Investment duration in months')),
                ('stage', models.CharField(choices=[('seed', 'Seed Stage'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('expansion', 'Expansion Stage')], default='seed', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='moderate', max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Investment'), ('funded', 'Fully Funded'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventures_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venture',
                'verbose_name_plural': 'Ventures',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Token Purchase'), ('investment', 'Investment'), ('return', 'Investment Return'), ('bonus', 'Bonus'), ('referral', 'Referral Reward'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='srt.partnercapitalaccount')),
                ('token_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srt.tokenpackage')),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='srt.venture')),
            ],
            options={
                'verbose_name': 'SRT Transaction',
                'verbose_name_plural': 'SRT Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentureInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_return', models.DecimalField(decimal_places=2, help_text='Expected return in SRT tokens', max_digits=15)),
                ('actual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='srt.partnercapitalaccount')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venture_investments', to=settings.AUTH_USER_MODEL)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='srt.venture')),
            ],
            options={
                'verbose_name': 'Venture Investment',
                'verbose_name_plural': 'Venture Investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
