# Generated by Django 5.1.5 on 2026-01-17 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_srt_integration'),
        ('srt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='srttransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srt_transactions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='ventureinvestment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srt_investments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='ventureinvestment',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='srt.venture'),
        ),
        migrations.CreateModel(
            name='TokenWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.DecimalField(decimal_places=2, help_text='Minimum withdrawal: 100 SRT', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Amount in NGN to be paid', max_digits=12)),
                ('bank_name', models.CharField(choices=[('access', 'Access Bank'), ('gtbank', 'GTBank'), ('first', 'First Bank'), ('uba', 'UBA'), ('zenith', 'Zenith Bank'), ('stanbic', 'Stanbic IBTC'), ('sterling', 'Sterling Bank'), ('union', 'Union Bank'), ('wema', 'Wema Bank'), ('fidelity', 'Fidelity Bank'), ('fcmb', 'FCMB'), ('polaris', 'Polaris Bank'), ('keystone', 'Keystone Bank'), ('ecobank', 'Ecobank'), ('heritage', 'Heritage Bank'), ('other', 'Other')], max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='srt.partnercapitalaccount')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Withdrawal',
                'verbose_name_plural': 'Token Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
