# Generated by Django 5.1.5 on 2026-01-17 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0002_add_srt_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenwithdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Withdrawal fee in NGN', max_digits=12),
        ),
    ]
