# Generated by Django 5.1.5 on 2026-07-01 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0005_venturetokenwithdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonus_tokens', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='srt.partnercapitalaccount')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srt.tokenpackage')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchase_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Purchase Intent',
                'verbose_name_plural': 'Token Purchase Intents',
                'ordering': ['-created_at'],
            },
        ),
    ]
