# Generated by Django 5.1.5 on 2026-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsmodule',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for module cards', null=True, upload_to='lms/modules/'),
        ),
    ]
