# Generated by Django 5.1.5 on 2026-01-15 08:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncubatorAcceleratorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='accelerator/')),
                ('application_info', ckeditor.fields.RichTextField(help_text='Information about the call for applications, eligibility, timeline, etc.')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_accepting_applications', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Incubator/Accelerator Page Content',
            },
        ),
        migrations.CreateModel(
            name='IncubatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=200)),
                ('applicant_name', models.CharField(default='', max_length=200)),
                ('applicant_email', models.EmailField(default='', max_length=254)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=20)),
                ('applicant_company', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='www.website.com')),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'Minimum Viable Product'), ('launched', 'Launched'), ('growing', 'Growing/Scaling')], default='idea', max_length=50)),
                ('industry', models.CharField(default='', help_text='e.g. FinTech, AgriTech, HealthTech', max_length=100)),
                ('application_text', ckeditor.fields.RichTextField(blank=True, default='', help_text='Describe your startup and what problem it solves')),
                ('traction', ckeditor.fields.RichTextField(blank=True, default='', help_text='Mention any traction, pilot users, revenue, etc.')),
                ('team_background', ckeditor.fields.RichTextField(blank=True, default='', help_text="Tell us about your team and why you're the right people to build this")),
                ('goals_for_program', models.TextField(blank=True, default='', help_text='What do you hope to achieve during the accelerator?')),
                ('funding_raised', models.CharField(blank=True, default='', help_text='e.g. $10,000 in grants, $5,000 from friends & family', max_length=100)),
                ('funding_needed', models.CharField(blank=True, default='', help_text='How much are you looking to raise post-program?', max_length=100)),
                ('pitch_deck', models.FileField(blank=True, default='', help_text='Upload your pitch deck (PDF, max 10MB)', upload_to='pitch_decks/')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
