# Generated by Django 5.1.5 on 2026-05-14 15:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incubatoracceleratorpage',
            options={'verbose_name': 'Incubator / Accelerator Page', 'verbose_name_plural': 'Incubator / Accelerator Page Settings'},
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='cta_body_closed',
            field=models.TextField(default="Applications are closed for this cycle. Join the waitlist and we'll notify you the moment the next cohort opens."),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='cta_body_open',
            field=models.TextField(default="Applications are open now. It takes about 20 minutes. There's nothing to lose."),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='cta_title_closed',
            field=models.CharField(default='Interested in the next cohort?', max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='cta_title_open',
            field=models.CharField(default='Ready to apply?', max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='curriculum_section_subtitle',
            field=models.TextField(default='Each week covers a new building block of your startup — with lessons, a practical exercise, and a deliverable you keep after the program.'),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='curriculum_section_title',
            field=models.CharField(default='One module per week. Built for idea-stage founders.', max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='good_fit_items',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Bullet list of reasons a founder IS a good fit. Use <ul><li> tags.'),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='hero_subtitle',
            field=models.TextField(default='A cohort-based accelerator for Nigerian founders at the idea and early-MVP stage. Curriculum. Mentorship. Community. A real chance at funding.'),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='hero_title',
            field=models.CharField(default='Build Your Idea Into a Business — With the Right Support', max_length=300),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='not_good_fit_items',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Bullet list of reasons a founder is NOT a good fit. Use <ul><li> tags.'),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='pillars_section_subtitle',
            field=models.TextField(default="LaunchPadi isn't just a course — it's a complete founder development experience built for the Nigerian ecosystem."),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='pillars_section_title',
            field=models.CharField(default='Four pillars. One transformative program.', max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='process_section_subtitle',
            field=models.CharField(default='Four simple steps. The whole process takes less than 30 minutes.', max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='stat_cost',
            field=models.CharField(default='Free', max_length=40),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='stat_event',
            field=models.CharField(default='Demo Day', max_length=60),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='stat_lessons',
            field=models.CharField(default='48+', max_length=20),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='stat_mentorship',
            field=models.CharField(default='1:1', max_length=40),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='stat_weeks',
            field=models.CharField(default='12', max_length=20),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='who_section_intro',
            field=models.TextField(default='LaunchPadi is highly selective. We look for founders with the right mindset and problem, not just a polished deck.'),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='who_section_title',
            field=models.CharField(default="You're the right fit if…", max_length=200),
        ),
        migrations.AlterField(
            model_name='incubatoracceleratorpage',
            name='application_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Short text shown in the sidebar above the deadline and apply button.'),
        ),
        migrations.AlterField(
            model_name='incubatoracceleratorpage',
            name='program_description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incubatoracceleratorpage',
            name='title',
            field=models.CharField(default='LaunchPadi Accelerator Program', max_length=200),
        ),
        migrations.CreateModel(
            name='ApplicationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='incubator.incubatoracceleratorpage')),
            ],
            options={
                'verbose_name': 'Application Step',
                'verbose_name_plural': 'Application Steps',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-star', help_text="FontAwesome icon class, e.g. 'fas fa-graduation-cap'", max_length=100)),
                ('icon_color', models.CharField(default='#26af59', help_text="CSS color for the icon, e.g. '#26af59'", max_length=30)),
                ('bg_color', models.CharField(default='rgba(38,175,89,0.1)', help_text="CSS background for the icon box, e.g. 'rgba(38,175,89,0.1)'", max_length=60)),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='incubator.incubatoracceleratorpage')),
            ],
            options={
                'verbose_name': 'Program Pillar',
                'verbose_name_plural': 'Program Pillars',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatWeLookForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-check', help_text='FontAwesome icon class', max_length=100)),
                ('icon_color', models.CharField(default='#26af59', max_length=30)),
                ('bg_color', models.CharField(default='rgba(38,175,89,0.1)', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_for_items', to='incubator.incubatoracceleratorpage')),
            ],
            options={
                'verbose_name': 'What We Look For',
                'verbose_name_plural': 'What We Look For (criteria)',
                'ordering': ['order'],
            },
        ),
    ]
