# Generated by Django 5.1.5 on 2026-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_incubator_page_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='look_for_section_title',
            field=models.CharField(default='What we look for in an application', help_text="Heading of the criteria card on the right side of the 'Who Should Apply' section.", max_length=200),
        ),
        migrations.AddField(
            model_name='incubatoracceleratorpage',
            name='not_good_fit_label',
            field=models.CharField(default='Not a good fit', help_text="Heading shown above the 'not a good fit' list, e.g. 'Not a good fit'", max_length=100),
        ),
    ]
