# Generated by Django 5.1.5 on 2026-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0003_add_who_section_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatorapplication',
            name='lms_provisioned',
            field=models.BooleanField(default=False, help_text='Set automatically when a student account and LMS enrollment have been created.'),
        ),
    ]
