# Generated by Django 5.1.5 on 2026-01-15 11:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Empowering African Startups', max_length=200)),
                ('hero_subtitle', models.TextField(default='Join the revolution in startup funding. Connect founders with investors, donors, and partners through innovative crowdfunding and token-based investments.')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_video_url', models.URLField(blank=True, help_text='Optional background video URL', null=True)),
                ('hero_cta_primary_text', models.CharField(default='Explore Projects', max_length=50)),
                ('hero_cta_primary_url', models.CharField(default='/projects/', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(default='Start a Project', max_length=50)),
                ('hero_cta_secondary_url', models.CharField(default='/projects/create/', max_length=200)),
                ('show_stats', models.BooleanField(default=True)),
                ('stat_1_value', models.CharField(default='$2.5M+', max_length=20)),
                ('stat_1_label', models.CharField(default='Total Funded', max_length=50)),
                ('stat_2_value', models.CharField(default='150+', max_length=20)),
                ('stat_2_label', models.CharField(default='Projects Launched', max_length=50)),
                ('stat_3_value', models.CharField(default='5,000+', max_length=20)),
                ('stat_3_label', models.CharField(default='Active Investors', max_length=50)),
                ('stat_4_value', models.CharField(default='12', max_length=20)),
                ('stat_4_label', models.CharField(default='African Countries', max_length=50)),
                ('show_how_it_works', models.BooleanField(default=True)),
                ('how_it_works_title', models.CharField(default='How StartUpRipple Works', max_length=100)),
                ('how_it_works_subtitle', models.TextField(default='Simple, transparent, and effective. Our platform connects innovative ideas with the resources they need to succeed.')),
                ('show_featured_projects', models.BooleanField(default=True)),
                ('featured_projects_title', models.CharField(default='Featured Projects', max_length=100)),
                ('featured_projects_subtitle', models.TextField(default='Discover innovative startups seeking funding')),
                ('show_srt_section', models.BooleanField(default=True)),
                ('srt_title', models.CharField(default='StartUp Ripple Tokens (SRT)', max_length=100)),
                ('srt_subtitle', models.TextField(default="A revolutionary way to invest in Africa's most promising startups")),
                ('srt_description', ckeditor.fields.RichTextField(default='SRT tokens allow you to diversify your investment across multiple vetted ventures. Purchase tokens, invest in curated opportunities, and earn returns as startups succeed.')),
                ('srt_image', models.ImageField(blank=True, null=True, upload_to='homepage/srt/')),
                ('srt_cta_text', models.CharField(default='Become a Partner', max_length=50)),
                ('srt_cta_url', models.CharField(default='/accounts/signup/', max_length=200)),
                ('show_incubator_section', models.BooleanField(default=True)),
                ('incubator_title', models.CharField(default='Accelerator Program', max_length=100)),
                ('incubator_subtitle', models.TextField(default='Take your startup to the next level')),
                ('incubator_description', ckeditor.fields.RichTextField(default='Our 12-week intensive program provides mentorship, funding, and resources to help early-stage startups scale rapidly.')),
                ('incubator_image', models.ImageField(blank=True, null=True, upload_to='homepage/incubator/')),
                ('incubator_cta_text', models.CharField(default='Apply Now', max_length=50)),
                ('incubator_cta_url', models.CharField(default='/incubator/apply/', max_length=200)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('testimonials_title', models.CharField(default='Success Stories', max_length=100)),
                ('testimonials_subtitle', models.TextField(default="Hear from founders and investors who've found success on our platform")),
                ('show_partners', models.BooleanField(default=True)),
                ('partners_title', models.CharField(default='Our Partners & Supporters', max_length=100)),
                ('show_cta_section', models.BooleanField(default=True)),
                ('cta_title', models.CharField(default='Ready to Make an Impact?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Join thousands of founders and investors building the future of African innovation')),
                ('cta_primary_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_primary_url', models.CharField(default='/accounts/signup/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_secondary_url', models.CharField(default='/cms/about/', max_length=200)),
                ('show_newsletter', models.BooleanField(default=True)),
                ('newsletter_title', models.CharField(default='Stay Updated', max_length=100)),
                ('newsletter_subtitle', models.TextField(default='Get the latest news on funding opportunities and startup success stories')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='homepage/partners/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-lightbulb', help_text='Font Awesome icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works_steps', to='cms.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
