# Generated by Django 5.1.5 on 2026-01-17 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepage_newslettersubscriber_partnerlogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('investment_risk', 'Investment Risk Disclosure'), ('privacy', 'Privacy Policy'), ('cookie', 'Cookie Policy'), ('refund', 'Refund Policy'), ('aml', 'Anti-Money Laundering Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or brief description', max_length=500)),
                ('content', ckeditor.fields.RichTextField(help_text='Main content of the page. Use the editor to format text.')),
                ('effective_date', models.DateField(blank=True, help_text='When this version of the document becomes effective', null=True)),
                ('version', models.CharField(default='1.0', help_text='Version number of this document', max_length=20)),
                ('is_published', models.BooleanField(default=True, help_text='Only published pages are visible to users')),
                ('show_table_of_contents', models.BooleanField(default=True, help_text='Auto-generate table of contents from headings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page_type'],
            },
        ),
    ]
