# Generated by Django 5.1.5 on 2026-01-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seed_legal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('investor_terms', 'Investor Terms'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('refund', 'Refund Policy'), ('aml', 'Anti-Money Laundering Policy')], max_length=20, unique=True),
        ),
    ]
