# Generated by Django 5.1.5 on 2026-01-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_socialmedialink_icon_class_alter_legalpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get in Touch', max_length=200)),
                ('hero_subtitle', models.TextField(default="Have questions about StartUpRipple? We'd love to hear from you. Send us a message and we'll respond as soon as possible.")),
                ('email', models.EmailField(default='hello@startupripple.com', max_length=254)),
                ('phone', models.CharField(default='+234 (0) 800 000 0000', max_length=50)),
                ('location', models.CharField(default='Lagos, Nigeria', max_length=200)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('form_title', models.CharField(default='Send us a Message', max_length=100)),
                ('office_hours', models.CharField(blank=True, default='Mon - Fri: 9:00 AM - 5:00 PM WAT', max_length=200)),
                ('show_map', models.BooleanField(default=True)),
                ('map_embed_code', models.TextField(blank=True, help_text='Google Maps embed code (iframe)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='ContactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.contactpage')),
            ],
            options={
                'verbose_name': 'Contact FAQ',
                'verbose_name_plural': 'Contact FAQs',
                'ordering': ['order'],
            },
        ),
    ]
