# Generated by Django 5.1.5 on 2026-02-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founder_registration_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Registration fee for Founders in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='investor_registration_fee',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Registration fee for Investors in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usd_to_ngn_rate',
            field=models.DecimalField(decimal_places=2, default=1600.0, help_text='Exchange rate: 1 USD = X NGN', max_digits=10),
        ),
    ]
