# Generated by Django 5.1.5 on 2026-05-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_registration_fee_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='incubator_youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=XXXXX)', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='incubator_subtitle',
            field=models.TextField(default="Africa's premier startup accelerator — turning bold ideas into thriving businesses"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='incubator_title',
            field=models.CharField(default='LaunchPadi Accelerator Program', max_length=100),
        ),
        migrations.CreateModel(
            name='AcceleratorGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/accelerator_gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_gallery', to='cms.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
