# Generated by Django 5.1.5 on 2026-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_add_accelerator_gallery_and_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_1_label',
            field=models.CharField(default='Cohorts Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_1_value',
            field=models.CharField(default='5+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_2_label',
            field=models.CharField(default='Startups Launched', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_2_value',
            field=models.CharField(default='120+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_3_label',
            field=models.CharField(default='Expert Mentors', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_3_value',
            field=models.CharField(default='50+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_4_label',
            field=models.CharField(default='Success Rate', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='incubator_stat_4_value',
            field=models.CharField(default='78%', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='incubator_youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://youtu.be/XXXXX)', null=True),
        ),
    ]
