# Generated by Django 5.1.5 on 2026-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_add_accelerator_stats_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startup_name', models.CharField(max_length=100)),
                ('cohort', models.CharField(blank=True, help_text='e.g. Cohort 1, 2024 Batch', max_length=50)),
                ('industry', models.CharField(blank=True, help_text='e.g. FinTech, AgriTech', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('outcome_tag', models.CharField(choices=[('raised', 'Raised Funding'), ('launched', 'Product Launched'), ('pivoted', 'Pivoted'), ('building', 'Still Building'), ('acquired', 'Acquired'), ('graduated', 'Graduated Program')], default='graduated', max_length=20)),
                ('outcome', models.CharField(help_text="One-line honest outcome, e.g. 'Raised ₦2M seed funding'", max_length=200)),
                ('outcome_detail', models.TextField(blank=True, help_text='2-3 sentences about the journey and result')),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Alumni Founder',
                'verbose_name_plural': 'Alumni Founders',
                'ordering': ['order', '-id'],
            },
        ),
    ]
