# Generated by Django 5.1.5 on 2026-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alumni_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_alumni_section',
            field=models.BooleanField(default=False),
        ),
    ]
