# Generated by Django 5.1.5 on 2026-05-14 14:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Partner With Nigeria's Startup Ecosystem", max_length=200)),
                ('hero_subtitle', models.TextField(default="Sponsor a LaunchPadi cohort, co-design a program, or access Nigeria's most promising idea-stage founders — before anyone else.")),
                ('intro_text', ckeditor.fields.RichTextField(default="<p>StartUp Ripple is not a fund. We are an ecosystem operator. We source and develop Nigeria's earliest-stage founders — and we do it with the support of corporates, NGOs, and development partners who share our vision for African innovation.</p>")),
                ('why_sponsor_text', ckeditor.fields.RichTextField(default="<ul><li>Direct access to pre-vetted, idea-stage Nigerian founders</li><li>Brand visibility across our founder and investor network</li><li>CSR impact reporting for development partners</li><li>Co-design programs aligned to your sector or mandate</li><li>First-look deal flow from each cohort's demo day</li></ul>")),
                ('show_tiers', models.BooleanField(default=True)),
                ('cta_text', models.CharField(default='Send Us an Enquiry', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsorship Page',
                'verbose_name_plural': 'Sponsorship Page',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Display price in USD', max_digits=10)),
                ('tagline', models.CharField(help_text='One-line value proposition', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='What this tier includes at a high level')),
                ('benefits', ckeditor.fields.RichTextField(help_text='Bullet list of specific sponsor benefits')),
                ('cohort_slots', models.PositiveIntegerField(default=0, help_text='Number of founder slots included')),
                ('icon_class', models.CharField(default='fas fa-star', help_text='Font Awesome icon class', max_length=50)),
                ('color_class', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('custom', 'Custom/Enterprise')], default='bronze', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this tier on the page')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sponsorship Tier',
                'verbose_name_plural': 'Sponsorship Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('organization_type', models.CharField(choices=[('corporate', 'Corporate Company'), ('ngo', 'NGO / Non-Profit'), ('dev_partner', 'Development Partner'), ('government', 'Government Agency'), ('other', 'Other')], default='corporate', max_length=20)),
                ('program_interest', models.TextField(help_text='What kind of program or cohort are they interested in?')),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under $5,000'), ('5k_15k', '$5,000 – $15,000'), ('15k_50k', '$15,000 – $50,000'), ('above_50k', '$50,000+'), ('tbd', 'To Be Discussed')], default='tbd', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('closed_won', 'Closed — Won'), ('closed_lost', 'Closed — Lost')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal team notes — not visible to the sponsor')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='sponsorship.sponsorshiptier')),
            ],
            options={
                'verbose_name': 'Sponsorship Inquiry',
                'verbose_name_plural': 'Sponsorship Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
