from django.core.management.base import BaseCommand
from apps.lms.models import LMSCourse, LMSModule, LMSLesson, LMSExercise, LMSDeliverable

MODULES = [
    {
        "week": 1,
        "title": "The Founder Mindset",
        "overview": "<p>Who you are as a founder matters as much as what you build. Most startup programs rush to the idea — this one starts with you. Your motivations, your blind spots, and the mental frameworks that will carry you through the hard parts of building something from nothing.</p><p>This week you will challenge yourself to answer the foundational question: <em>why are you really doing this?</em> The answers will surprise you — and they'll become the bedrock of every decision you make as a founder.</p>",
        "objectives": "<ul><li>Identify your core motivation for building a startup</li><li>Understand the difference between a founder mindset and an employee mindset</li><li>Build a personal resilience toolkit for the challenges ahead</li><li>Write a founder manifesto that anchors your journey</li></ul>",
        "lessons": [
            ("Why Founders Fail — and It's Rarely the Idea", 12, "<h2>The Real Reasons Startups Die</h2><p>CB Insights analysed 101 startup post-mortems and found that <strong>only 42% failed because of market problems</strong>. The rest failed because of founder issues: co-founder conflict, burnout, loss of passion, or an inability to pivot when the world changed.</p><p>The idea is almost never the problem. The founder is both the asset and the liability.</p><h3>The Three Founder Failure Modes</h3><ol><li><strong>The Dreamer</strong> — falls in love with the idea, not the problem. Spends years building without validating. Refuses feedback because it threatens the dream.</li><li><strong>The Technician</strong> — confuses execution with strategy. Builds excellent products nobody buys because they never talked to a customer.</li><li><strong>The Quitter</strong> — treats every obstacle as a sign they should stop. Has never learned that building requires iterating through failure, not avoiding it.</li></ol><h3>What Successful Founders Have in Common</h3><p>Research from First Round Capital's 10-year study of 300 startups found that the best founders share four traits: <em>coachability, drive, resilience, and clarity of vision</em>. None of these are natural talents. All of them are practised.</p><blockquote>\"The most dangerous thing a founder can do is mistake activity for progress.\" — Y Combinator</blockquote><p>This week is about building the self-awareness to know which failure mode you're closest to — and choosing a different path before it's too late.</p>"),
            ("Discovering Your Why", 10, "<h2>Simon Sinek Was Only Half Right</h2><p>\"Start with why\" is famous advice. But Sinek's framework is usually applied to companies — not to the founder themselves. Before you can build a company with a clear purpose, you need a founder with a clear purpose.</p><h3>The Three Levels of Motivation</h3><p>Research by Edward Deci and Richard Ryan identifies three types of motivation that predict persistence:</p><ul><li><strong>External motivation</strong> — you want money, status, or validation. This runs out when the cheques stop coming and the praise stops flowing.</li><li><strong>Identified motivation</strong> — you believe what you're doing matters, even if it's hard. More durable, but can still fade.</li><li><strong>Intrinsic motivation</strong> — you find the work itself meaningful and engaging. This is what founders who thrive over 7–10 years are running on.</li></ul><h3>The Five Why Exercise</h3><p>Ask yourself: <em>Why do I want to build this?</em> Write the answer. Then ask why again. And again — five times. Each answer reveals a deeper layer of your actual motivation.</p><p>Example:</p><blockquote>Why do I want to build a logistics startup?<br>→ Because deliveries in Lagos are a mess.<br>Why does that matter to you?<br>→ My mother's small business lost customers because deliveries were unreliable.<br>Why does her business matter?<br>→ It's how our family ate during lean years. Reliability was dignity.<br>Why do you need to be the one to fix this?<br>→ I understand this world — I grew up in it. I know the frustration from both sides.<br>Why now?<br>→ Smartphones have made this solvable in a way they weren't five years ago.</blockquote><p>That founder has a <em>real</em> why. It's not \"logistics is a $50B market.\" It's personal, specific, and durable.</p>"),
            ("Building Resilience and Dealing with Uncertainty", 15, "<h2>The Uncertainty Is the Job</h2><p>Every founder — without exception — faces a moment where nothing is working, everyone doubts them, and they question whether to continue. This is not a sign that you've chosen the wrong path. It is the path.</p><h3>What Resilience Actually Looks Like</h3><p>Resilience is not toughness. It is not the ability to feel no pain. It is the ability to feel the full weight of a setback and choose to continue anyway — and to recover faster each time.</p><p>Three practices that build genuine resilience:</p><ol><li><strong>Reframe failure as information.</strong> When something doesn't work, ask: what did I learn? What would I do differently? This keeps you in a learning posture instead of a victimhood posture.</li><li><strong>Build a support system before you need it.</strong> Identify 3 people in your life who will tell you the truth and still believe in you. Not cheerleaders — truth-tellers who care.</li><li><strong>Control the controllables.</strong> Write down your worries and separate them into two lists: things you can influence and things you can't. Spend zero energy on the second list.</li></ol><h3>Dealing with Ambiguity</h3><p>Most people are comfortable with uncertainty in their personal lives — they don't know who they'll marry, where they'll live in 10 years, what their health will be. But in business, uncertainty feels different because there are stakes attached.</p><p>The antidote is not a plan — it's a process. Build the habit of making the best decision you can with the information you have, acting on it, gathering feedback, and adjusting. This is all that successful founders do. They just do it faster and with less emotional attachment to being right.</p>"),
            ("The Growth Mindset in Practice", 8, "<h2>Beyond the Buzzword</h2><p>Carol Dweck's \"growth mindset\" research is real and powerful — but the phrase has become so overused that most people nod along without actually changing their behaviour.</p><p>A growth mindset in practice means one specific thing: <strong>you believe that your current abilities are a starting point, not a ceiling.</strong></p><h3>The Founder-Specific Application</h3><p>Here is where founders most often reveal a fixed mindset without realising it:</p><ul><li><strong>Pitching:</strong> \"I'm just not a natural salesperson.\" (Fixed) vs. \"I haven't figured out how to tell this story yet.\" (Growth)</li><li><strong>Technical skills:</strong> \"I'm not a developer — I can't build.\" (Fixed) vs. \"I need to find a technical co-founder or learn the basics.\" (Growth)</li><li><strong>Rejection:</strong> \"The investor said no — my idea must be bad.\" (Fixed) vs. \"That investor said no — what did I learn about who my real audience is?\" (Growth)</li></ul><h3>The One Habit That Changes Everything</h3><p>At the end of every week, write down one thing that didn't go as planned and one thing you learned from it. That's it. That one practice, done consistently, is the entire growth mindset in action. Over 52 weeks it compounds into an entirely different way of seeing the world.</p>")
        ],
        "exercise_title": "The Five Whys — Your Founder Motivation",
        "exercise_instructions": "<p>Take 30 minutes in a quiet space and work through this exercise in writing.</p><ol><li>Write your answer to: <em>\"Why do I want to build this business or startup idea?\"</em></li><li>Ask \"why\" to your answer. Write that answer.</li><li>Repeat 5 times, going deeper each round.</li><li>Review your final answer. Is it personal, specific, and durable?</li><li>Write one sentence that captures your core motivation — your founder \"why.\"</li></ol>",
        "exercise_tips": "<p><strong>Don't rush this.</strong> Many founders realise in this exercise that their stated motivation (\"I want to make money\") is not their real motivation (\"I want to prove something to my family\"). Both are valid — but you need to know the truth.</p>",
        "deliverable_title": "Founder Manifesto",
        "deliverable_desc": "<p>Write a 1-page Founder Manifesto that captures:</p><ul><li>Your core motivation (why you are building)</li><li>The problem that keeps you up at night</li><li>What success looks like for you in 3 years — not just metrics, but how it feels</li><li>One value you will never compromise, no matter the pressure</li></ul><p>This is a living document. You will revise it. But write it honestly today.</p>",
        "deliverable_format": "1-page PDF or Google Doc",
    },
    {
        "week": 2,
        "title": "Problem Discovery",
        "overview": "<p>The best startups start with a deeply-understood problem, not a solution. Most first-time founders build something they <em>think</em> people want, show it to the world, and are confused when nobody cares. The reason is almost always the same: they skipped the problem discovery step.</p><p>This week you will learn how to identify problems worth solving — and more importantly, how to tell the difference between a real problem and an interesting idea.</p>",
        "objectives": "<ul><li>Understand the difference between a problem and a solution</li><li>Learn how to conduct customer discovery interviews that reveal real insight</li><li>Apply the Jobs-to-Be-Done framework to your idea</li><li>Write a problem statement backed by real evidence</li></ul>",
        "lessons": [
            ("The Problem-First Mindset", 10, "<h2>Fall in Love with the Problem, Not the Solution</h2><p>Uri Levine, founder of Waze, says this is the single most important thing he ever learned about building startups. Almost every successful company is built on a deeply understood problem — not a clever feature set.</p><p>WhatsApp solved the problem of expensive SMS in developing markets. M-Pesa solved the problem of financial exclusion for people without bank accounts. Google solved the problem of finding information in a rapidly growing internet.</p><p>In each case, the founders could describe the problem in one sentence before they could describe the solution. That's the test.</p><h3>How to Know if You Have a Real Problem</h3><p>A real problem has three characteristics:</p><ol><li><strong>People are actively trying to solve it.</strong> They're using workarounds, paying for imperfect alternatives, or spending significant time on it. If nobody is doing anything about the problem, it may not be painful enough to build a business around.</li><li><strong>It's painful frequently.</strong> A problem that occurs once a year is not a business. A problem that occurs weekly or daily is.</li><li><strong>People will pay to have it solved.</strong> Not everyone — but enough people at a price that makes the math work.</li></ol><h3>The Frequency-Intensity Grid</h3><p>Plot your problem on two axes: how <em>often</em> does it occur (frequency) vs. how <em>badly</em> it hurts (intensity). The best problems are high-frequency and high-intensity. But a low-frequency, very high-intensity problem (e.g., legal emergencies) can also be a strong business if the willingness to pay is high.</p>"),
            ("How to Run Customer Discovery Interviews", 20, "<h2>The Most Important Skill You're Not Taught in School</h2><p>Customer discovery interviews are not market research surveys. They are not focus groups. They are one-on-one conversations where your job is to listen — not to pitch.</p><h3>The Rules of Customer Discovery</h3><ol><li><strong>Never mention your solution.</strong> The moment you describe your idea, the person you're interviewing will start responding to your idea rather than telling you about their life. Save your solution for a different conversation.</li><li><strong>Ask about the past, not the hypothetical.</strong> \"Would you use something like this?\" is a useless question. \"Tell me about the last time this problem happened to you\" is gold.</li><li><strong>Follow the emotion.</strong> When someone says \"it's fine\" or \"whatever\" — that's not interesting. When they say \"it drives me insane\" or \"it cost me a client\" — ask more.</li><li><strong>Shut up.</strong> Most interviewers talk 40% of the time. You should be talking 20% of the time.</li></ol><h3>The Interview Guide</h3><p>Use this structure for your first 5 interviews:</p><ol><li>Introduction (2 min): Thank them, explain you're learning about their experience, assure them there's no right or wrong answer</li><li>Context questions (5 min): Who are they? What do they do? What does their typical day/week look like?</li><li>Problem exploration (15 min): Tell me about the last time [the problem] happened. What did you do? How did that feel? What did you try? What worked and what didn't?</li><li>Wrap up (3 min): What else should I know? Who else deals with this?</li></ol><p>Take notes. Record with permission. Review immediately after.</p>"),
            ("Spotting Real Pain vs. Nice-to-Have", 8, "<h2>The Painkiller vs. Vitamin Test</h2><p>Investors often ask: is your product a painkiller or a vitamin? A vitamin is something people know they should have but won't miss if they don't take it today. A painkiller is something people will go out of their way to find when the pain hits.</p><p>The honest answer for most early-stage startups is: we don't know yet. But here's how to find out.</p><h3>Three Signals of Real Pain</h3><ol><li><strong>Current spend.</strong> Are people already paying for an imperfect alternative? If someone is paying ₦50,000/month for a manual workaround to the problem you want to solve, the pain is real.</li><li><strong>Active search.</strong> Are people Googling solutions? Asking in Facebook groups? Posting questions on Twitter? Unsolicited demand is the most honest signal.</li><li><strong>Emotional language.</strong> When you ask people about the problem, do they use strong emotional words? Frustration, embarrassment, anger, anxiety? Or do they shrug?</li></ol>"),
            ("The Jobs-to-Be-Done Framework", 12, "<h2>What People Are Actually Hiring Your Product to Do</h2><p>Clayton Christensen's Jobs-to-Be-Done (JTBD) framework is one of the most powerful lenses in product thinking. The insight: people don't buy products — they <em>hire</em> them to get a job done.</p><p>The classic example: people don't buy a drill. They hire a drill to make a hole. They hire a hole to hang a picture. They hire a picture to feel at home.</p><p>When you understand the actual job being hired, you realise the competition is different from what you thought. The drill doesn't compete with other drills — it competes with anything that can make a hole: a hammer and nail, a professional handyman, a pre-drilled shelf.</p><h3>Applying JTBD to Your Problem</h3><p>For your startup idea, complete this statement:</p><p><em>\"When [situation], I want to [motivation], so I can [outcome].\"</em></p><p>Example for a ride-hailing app in Lagos:</p><blockquote>When I need to get somewhere important quickly, I want reliable transport that arrives when I need it, so I can arrive on time without stress.</blockquote><p>The job is not \"I need a ride.\" The job is \"I need to arrive on time without stress.\" That distinction changes everything about what you build and how you talk about it.</p>")
        ],
        "exercise_title": "5 Customer Discovery Interviews",
        "exercise_instructions": "<p>Conduct 5 customer discovery interviews this week. Use the following guide:</p><ol><li>Identify 5 people who experience the problem you want to solve. They should not be close friends or family.</li><li>Reach out and ask for 20–25 minutes of their time. Be honest: you're researching a problem, not pitching anything.</li><li>During each interview: ask about their past experience, not hypotheticals. Listen more than you talk. Follow emotional cues.</li><li>After each interview: write 3 key insights within 30 minutes of the conversation.</li><li>After all 5: look for patterns. What do 3 or more people share?</li></ol>",
        "exercise_tips": "<p><strong>Can't find strangers to interview?</strong> Start with weak ties — people you know slightly but not well. LinkedIn, community groups, church contacts, alumni networks. The goal is people who experience the problem, not people who like you.</p>",
        "deliverable_title": "Problem Statement Document",
        "deliverable_desc": "<p>Write a Problem Statement Document with the following sections:</p><ol><li><strong>The Problem (1 sentence):</strong> State the core problem clearly and specifically.</li><li><strong>Who Has It:</strong> Describe the person who experiences this problem most acutely. Be specific.</li><li><strong>Evidence from Interviews (3–5 direct quotes):</strong> Quote specific things people said in your discovery interviews.</li><li><strong>Why It Exists Today:</strong> What structural, technological, or behavioural reason has prevented this from being solved?</li><li><strong>How People Cope Today:</strong> What workarounds, tools, or services do they currently use?</li></ol>",
        "deliverable_format": "1–2 page document (PDF, Word, or Google Doc)",
    },
    {
        "week": 3,
        "title": "Market Research & Sizing",
        "overview": "<p>You need to know how big your opportunity is — not to impress investors with a big number, but to make smart decisions about whether this market can support the business you want to build. A great solution to a tiny problem can still be a bad business.</p><p>This week you'll learn to research your market properly and size it in a way that is honest, useful, and defensible.</p>",
        "objectives": "<ul><li>Calculate a realistic TAM, SAM, and SOM for your idea</li><li>Conduct primary and secondary market research</li><li>Map the competitive landscape honestly</li><li>Identify market trends that support (or threaten) your timing</li></ul>",
        "lessons": [
            ("TAM, SAM, SOM Explained Simply", 12, "<h2>The Three Market Sizes Every Founder Must Know</h2><p><strong>TAM (Total Addressable Market)</strong> — the total revenue opportunity if you captured 100% of the market. This is a theoretical maximum. Example: if you're building a ride-hailing app in Nigeria, the TAM might be all personal transportation spending in Nigeria.</p><p><strong>SAM (Serviceable Addressable Market)</strong> — the portion of the TAM you can realistically target given your current product and geography. For a Lagos-based ride-hailing app starting in Lekki, the SAM is Lagos-based smartphone users who take 3+ car trips per week.</p><p><strong>SOM (Serviceable Obtainable Market)</strong> — the slice of the SAM you can realistically capture in 3–5 years given your resources and competition. This is what matters for your business plan.</p><h3>The Bottom-Up Approach</h3><p>The most credible market sizing starts from the bottom up, not from industry reports. Instead of saying \"the ride-hailing market in Africa is $5B and we want 1%,\" try:</p><ul><li>There are 2 million regular commuters in Lagos</li><li>We estimate 20% use app-based transport (400,000)</li><li>Average spend: ₦15,000/month</li><li>SAM = ₦6 billion per month (≈$3.75M/month)</li><li>Year 1 target: 1% = ₦60M/month</li></ul><p>This is far more credible to any investor or partner because you can defend each assumption.</p>"),
            ("Primary vs. Secondary Research", 10, "<h2>Where the Real Insights Come From</h2><p><strong>Secondary research</strong> is data that already exists: industry reports, government statistics, academic papers, news articles, competitor analysis. It's fast and free (or cheap). Use it to understand the landscape before you start talking to people.</p><p><strong>Primary research</strong> is data you collect yourself: customer interviews, surveys, observation, usage data. It's slower and harder but produces insights no report can give you.</p><h3>Sources for Nigerian Market Research</h3><ul><li>National Bureau of Statistics (NBS) — population, income, economic data</li><li>Central Bank of Nigeria (CBN) — financial sector data</li><li>Lagos State Government reports — urban-specific data</li><li>Statista, McKinsey, PwC Africa reports — sector trends</li><li>AfricaBriefing, Disrupt Africa, TechCabal — startup-specific data</li><li>Your own customer interviews — always the most valuable</li></ul>"),
            ("Mapping the Competitive Landscape", 12, "<h2>You Have Competition — Even If You Think You Don't</h2><p>\"We have no competition\" is one of the most dangerous phrases a founder can say. It usually means one of three things: the problem isn't real (no one has tried to solve it), you haven't done enough research (someone is already solving it), or your competition is the status quo (people are doing nothing, and convincing them to change is your real challenge).</p><h3>The Competitive Matrix</h3><p>Map your competitors on two axes that matter most to your customer. For a fintech in Nigeria, that might be: ease of use vs. interest rates. For a logistics startup: speed vs. price.</p><p>Look for a position on the map that is unoccupied or underserved. That gap — if it aligns with what customers actually want — is your opportunity.</p><h3>What to Research for Each Competitor</h3><ul><li>Their pricing model</li><li>Their distribution channels</li><li>Their main customer segments</li><li>Their known weaknesses (read their 1-star reviews)</li><li>Their recent funding or growth news</li></ul>"),
            ("Market Trends and Timing", 8, "<h2>Why Now?</h2><p>One of the most important questions investors ask — and one most founders aren't prepared for — is: why is now the right time to build this? The answer requires understanding the trends that are making your solution possible or necessary today when it wasn't 3 years ago.</p><h3>Four Types of Trends to Watch</h3><ol><li><strong>Technology shifts</strong> — what has recently become possible or cheap? (Smartphones, AI, mobile payments, broadband)</li><li><strong>Regulatory changes</strong> — what has the government recently allowed or required?</li><li><strong>Behaviour shifts</strong> — what have consumers recently started doing or stopped doing?</li><li><strong>Economic shifts</strong> — what has changed about income levels, cost structures, or purchasing patterns?</li></ol><p>For Nigerian founders, the most powerful recent trends include: rapid smartphone penetration, Fintech regulation opening (PSB licences), the growth of informal commerce, and a young population willing to adopt new tools.</p>")
        ],
        "exercise_title": "Market Sizing Worksheet",
        "exercise_instructions": "<p>Complete a bottom-up market sizing for your idea:</p><ol><li>Define your target customer as specifically as possible (age, location, behaviour, income)</li><li>Estimate how many of these people exist in your primary market (Nigeria, Lagos, etc.)</li><li>Estimate how much they currently spend on the problem (per month or year)</li><li>Calculate your SAM (target customers × current spend)</li><li>Set a realistic SOM target for Year 1 (what % of SAM can you capture in 12 months?)</li><li>Research 3 existing players in your space and write one paragraph on each</li></ol>",
        "exercise_tips": "<p>Don't obsess over getting the number exactly right. Focus on building assumptions you can defend. A ₦500M SAM with clear, honest assumptions is more valuable than a ₦50B TAM you can't explain.</p>",
        "deliverable_title": "Market Research Brief",
        "deliverable_desc": "<p>Write a 2-page Market Research Brief covering:</p><ol><li><strong>Market Size:</strong> Your bottom-up TAM, SAM, and SOM with the assumptions behind each number</li><li><strong>Target Customer:</strong> One paragraph describing your ideal early adopter</li><li><strong>Competitive Landscape:</strong> A 2×2 matrix plotting your 4 key competitors plus a paragraph explaining your differentiated position</li><li><strong>Key Market Trends:</strong> 3 trends that make this the right time to build</li></ol>",
        "deliverable_format": "2-page document or structured Google Slides",
    },
    {
        "week": 4,
        "title": "Customer Segmentation & Personas",
        "overview": "<p>\"Everyone\" is not a customer. One of the most common and costly mistakes early-stage founders make is trying to serve everyone at once — and ending up with a product so generic it compels nobody. This week you'll learn to identify your most valuable early customer and understand them so deeply that your product, messaging, and pricing write themselves.</p>",
        "objectives": "<ul><li>Understand why segmentation is essential for early-stage startups</li><li>Apply demographic and psychographic segmentation to your market</li><li>Build two detailed customer personas grounded in real research</li><li>Identify the characteristics of your ideal early adopter</li></ul>",
        "lessons": [
            ("Why Segmentation Matters for Startups", 8, "<h2>The Narrower You Go, the Further You Get</h2><p>Counterintuitively, the more specifically you define your initial customer, the faster you grow. This is because a laser-focused product creates passionate word-of-mouth among a specific group, which is far more powerful than lukewarm interest from a broad audience.</p><p>Facebook started at Harvard. Uber started in San Francisco. M-Pesa started with Kenyan Safaricom users. WhatsApp started with people who had just bought smartphones and wanted free SMS.</p><p>None of them started with \"everyone.\"</p><h3>The 1,000 True Fans Theory</h3><p>Kevin Kelly's famous essay argues that any creator or business that has 1,000 people who love them — not like them, <em>love</em> them — can sustain a business. For a startup, your job in Year 1 is to find the 100 people who love your product so much they'd be genuinely upset if it disappeared. Everything else follows from there.</p>"),
            ("Demographic vs. Psychographic Segmentation", 10, "<h2>Beyond Age and Gender</h2><p><strong>Demographic segmentation</strong> — age, gender, income, location, education — tells you who someone is. It's the starting point but not the destination.</p><p><strong>Psychographic segmentation</strong> — values, attitudes, interests, lifestyle, behaviour — tells you why they make decisions. This is where the insight is.</p><h3>Example: Lagos Digital Banking Customer</h3><p>Demographics: Female, 28–35, Lagos Island, earns ₦150–350K/month, university educated</p><p>Psychographics: Values convenience over cost, early adopter of tech products, frustrated by queues and paperwork, embarrassed by cash — prefers digital, influences her peer group's choices, active on Instagram</p><p>The demographic profile tells you where to find her. The psychographic profile tells you how to speak to her, what features she'll pay for, and what will make her recommend your product to her friends.</p>"),
            ("Building a Customer Persona", 12, "<h2>Making Your Ideal Customer Real</h2><p>A customer persona is a semi-fictional character built from research that represents your ideal customer segment. The goal is not to build a demographic average — it's to build a specific, believable person you can make decisions about.</p><h3>The Persona Template</h3><p>A useful persona has:</p><ul><li><strong>Name and photo</strong> (fictional but specific — \"Amaka, 31\" not \"Female professional\")</li><li><strong>Job and income</strong></li><li><strong>Daily routine and context</strong></li><li><strong>Goals and aspirations</strong> — what does she want in life and work?</li><li><strong>Frustrations and pain points</strong> — especially related to the problem you're solving</li><li><strong>Current workarounds</strong> — what does she do today to cope?</li><li><strong>Key channels</strong> — where does she find information, recommendations, products?</li><li><strong>Buying triggers</strong> — what would make her try something new?</li><li><strong>Barriers</strong> — what would make her not switch?</li></ul>"),
            ("Finding Your Early Adopters", 8, "<h2>The First 100 Are the Most Important</h2><p>Early adopters are not the same as your long-term customers. They are willing to tolerate an imperfect product because they have a strong enough problem and enough curiosity to try new things. Finding them is a critical early task.</p><h3>Characteristics of Early Adopters</h3><ul><li>They are actively aware of the problem and frustrated by it</li><li>They have already tried other solutions and found them lacking</li><li>They are open to risk — they try new things, they don't wait for social proof</li><li>They are vocal — they will tell others, both positively and negatively</li></ul><h3>Where to Find Them</h3><p>Look for people who are complaining about the problem publicly: Twitter threads, Facebook groups, Reddit, industry forums, LinkedIn posts. These are your earliest signals. The person who posted \"Can someone tell me why [your problem] is still so broken in 2024?\" is your early adopter.</p>")
        ],
        "exercise_title": "Build Two Customer Personas",
        "exercise_instructions": "<p>Using the persona template from Lesson 3, create two detailed customer personas for your target market.</p><ol><li>Each persona should be based on insights from your Week 2 customer interviews</li><li>Give each persona a name, a brief backstory, and a photo (you can use a stock photo)</li><li>Complete all sections of the template for each persona</li><li>End each persona with: \"This person would use my product because...\" and \"This person would NOT use my product because...\"</li></ol>",
        "exercise_tips": "<p>The second persona should represent a different segment from the first — perhaps a different income bracket, geography, or use case. This forces you to think about which segment to focus on first.</p>",
        "deliverable_title": "Customer Persona Document",
        "deliverable_desc": "<p>A formatted document containing two complete customer personas, each with:</p><ul><li>Name, photo, age, location, income</li><li>Goals and aspirations</li><li>Frustrations and pain points (related to your problem)</li><li>Current workarounds and tools</li><li>Key channels and buying triggers</li><li>Barriers to switching</li><li>One paragraph on why this persona is or isn't your primary target</li></ul>",
        "deliverable_format": "Document or presentation (PDF, Google Slides, Canva)",
    },
    {
        "week": 5,
        "title": "Solution Design & MVP Thinking",
        "overview": "<p>The MVP is one of the most misunderstood concepts in the startup world. Most founders either build too much (a fully-featured product that took 18 months) or too little (a landing page they call an MVP). This week you'll learn what an MVP really is, why it works, and how to design one that actually tests your most important assumptions — without writing a single line of code.</p>",
        "objectives": "<ul><li>Define MVP accurately and understand what it is not</li><li>Identify and rank the key assumptions behind your idea</li><li>Create a low-fidelity prototype or paper prototype</li><li>Design experiments to test your most critical assumptions</li></ul>",
        "lessons": [
            ("What is an MVP and What it Isn't", 10, "<h2>Minimum Viable Product: A Definition That Actually Helps</h2><p>Eric Ries defined the MVP as \"the version of a new product that allows a team to collect the maximum amount of validated learning about customers with the least effort.\"</p><p>Note what it doesn't say: the minimum viable product is not the product with the fewest features. It's the product that teaches you the most, fastest.</p><h3>Famous MVPs That Looked Nothing Like the Final Product</h3><ul><li><strong>Dropbox</strong> — Drew Houston's MVP was a 3-minute video explaining how the product would work. No product existed. The video got 75,000 signups overnight.</li><li><strong>Zappos</strong> — Nick Swinmurn's MVP was to take photos of shoes at local stores and list them on a basic website. When someone bought a pair, he'd go buy them from the store and ship them. No inventory. No logistics. Just testing: will people buy shoes online?</li><li><strong>Airbnb</strong> — The founders' MVP was a simple website listing their own apartment in San Francisco during a design conference. Three guests. Air mattresses. Breakfast included.</li></ul><h3>What Makes an MVP Valid</h3><p>An MVP is valid if it tests a specific assumption. Before building yours, write down: \"This MVP will test whether [assumption].\" If you can't complete that sentence, you don't have an MVP — you have a product.</p>"),
            ("Assumption Mapping", 12, "<h2>What Do You Believe That Might Not Be True?</h2><p>Every startup is built on a stack of assumptions. The job of early-stage work is to find and test the riskiest ones before investing significant time or money.</p><h3>How to Build an Assumption Map</h3><ol><li>Write down every assumption behind your idea. Include assumptions about: customer behaviour, willingness to pay, technology, partnerships, regulation, and the team.</li><li>Rate each assumption on two axes: <em>how important is it?</em> (if this is wrong, our business fails) and <em>how certain are we?</em> (how much evidence do we have?)</li><li>Your MVP should test the assumptions that are high importance + low certainty first.</li></ol><h3>Common Untested Assumptions</h3><ul><li>\"Customers will pay ₦X for this\" — almost always untested</li><li>\"People will change their current behaviour\" — the hardest assumption of all</li><li>\"We can acquire customers at ₦Y cost\" — usually optimistic</li><li>\"Our supplier/partner will work with us\" — often assumed, rarely confirmed</li></ul>"),
            ("Prototyping Without Code", 15, "<h2>The Fastest Way to Test an Idea</h2><p>A prototype is not a product. A prototype is a simulation of a product that lets you gather feedback without building anything real. The best founders can test ideas in days with nothing more than paper, Figma, a WhatsApp message, or a Google Form.</p><h3>Types of Prototypes (from lowest to highest fidelity)</h3><ol><li><strong>Paper prototype</strong> — draw your screens on paper. Show them to people. Ask them to \"tap\" what they would tap. You'll learn in 20 minutes what a developer would take 2 weeks to build and show you.</li><li><strong>Clickable wireframe</strong> — use Figma, Balsamiq, or Canva to build a clickable mock-up. No code. Users can \"use\" your product and you can watch where they get confused.</li><li><strong>Wizard of Oz MVP</strong> — your product appears automated but is actually manually operated behind the scenes. The first version of many successful products worked this way.</li><li><strong>Concierge MVP</strong> — you do the service manually for your first customers, learning what they actually need before automating it.</li></ol>"),
            ("The Build-Measure-Learn Loop", 8, "<h2>The Engine of Early-Stage Progress</h2><p>Lean Startup's Build-Measure-Learn loop is simple in theory and brutally difficult in practice. The loop says: build the smallest thing that tests your assumption, measure the result honestly, and decide whether to continue (persevere) or change direction (pivot).</p><p>The difficulty is the \"honestly\" part. Most founders measure the metrics that make them feel good (signups, page views) rather than the metrics that tell them if their business works (retention, revenue, referrals).</p><h3>Choose the Right Metric for Each Stage</h3><ul><li><strong>Stage: Problem validation</strong> → Metric: % of interviewees who confirm the problem and describe current workarounds</li><li><strong>Stage: Solution validation</strong> → Metric: % of users who try your prototype and say they would pay for it</li><li><strong>Stage: Pricing validation</strong> → Metric: % who complete a payment (not just agree to in a survey)</li><li><strong>Stage: Retention</strong> → Metric: % of users who come back after first use</li></ul>")
        ],
        "exercise_title": "Paper Prototype and User Test",
        "exercise_instructions": "<p>This week you will build and test a prototype of your MVP.</p><ol><li>List the top 3 assumptions behind your idea (from the Assumption Mapping lesson)</li><li>Design the simplest version of your product that would test your #1 assumption. This can be: paper sketches, a Figma mockup, a Google Form, a WhatsApp message, or a landing page</li><li>Test your prototype with 3 people from your Week 4 persona. Show it to them without explaining — observe where they get confused or excited</li><li>Write down the 3 biggest things you learned from the tests</li></ol>",
        "exercise_tips": "<p>Don't defend your prototype when testers are confused. Their confusion is data. Say \"interesting — what were you expecting there?\" instead of \"let me explain how it works.\"</p>",
        "deliverable_title": "MVP Feature List",
        "deliverable_desc": "<p>Submit a one-page MVP Feature List containing:</p><ol><li><strong>The #1 Assumption You're Testing:</strong> One sentence</li><li><strong>MVP Description:</strong> What is the simplest version of your product that tests this assumption?</li><li><strong>3 Core Features:</strong> For each feature, write: (a) what it does, (b) which assumption it tests, (c) what \"validated\" looks like</li><li><strong>What You Are NOT Building:</strong> List 3–5 things that seem important but are out of scope for the MVP and why</li><li><strong>Test Results Summary:</strong> What did you learn from your prototype tests?</li></ol>",
        "deliverable_format": "1-page document",
    },
    {
        "week": 6,
        "title": "Business Model Design",
        "overview": "<p>A great product without a business model is a charity — and charities have their own funding challenges. This week you'll learn to design a sustainable business model from the ground up: how you create value, deliver it, and capture enough of it to keep going.</p><p>Many founders skip this step because it feels like \"business school stuff.\" But the founders who think carefully about their business model from the start avoid the trap of building something people love but can't figure out how to monetise.</p>",
        "objectives": "<ul><li>Complete a Business Model Canvas for your idea</li><li>Understand and choose the right revenue model for your market</li><li>Design a pricing strategy grounded in customer psychology</li><li>Calculate basic unit economics: CAC, LTV, and payback period</li></ul>",
        "lessons": [
            ("The Business Model Canvas", 15, "<h2>Nine Building Blocks of Any Business</h2><p>Alexander Osterwalder's Business Model Canvas is the best single-page tool for thinking about how a business works. It maps nine building blocks:</p><ol><li><strong>Customer Segments</strong> — who are you creating value for?</li><li><strong>Value Propositions</strong> — what value do you deliver? What problem do you solve?</li><li><strong>Channels</strong> — how do you reach customers?</li><li><strong>Customer Relationships</strong> — what type of relationship does each segment expect?</li><li><strong>Revenue Streams</strong> — how does the business make money?</li><li><strong>Key Resources</strong> — what assets are essential to deliver value?</li><li><strong>Key Activities</strong> — what must you do well to deliver value?</li><li><strong>Key Partnerships</strong> — who can you rely on to do what you can't do yourself?</li><li><strong>Cost Structure</strong> — what costs are inherent in delivering value?</li></ol><p>The power of the canvas is that you can see how changes in one block affect the others. Change your distribution channel, and your cost structure changes. Change your customer segment, and your value proposition may need to change.</p>"),
            ("Revenue Models for African Startups", 10, "<h2>How Will You Actually Make Money?</h2><p>The right revenue model depends on your product, your customer, and your market. Here are the most common models and when each works best:</p><ul><li><strong>Transaction fees</strong> — charge a % of each transaction. Works when you're an intermediary (Paystack, Jumia). Scales with volume but requires large GMV to be meaningful.</li><li><strong>Subscriptions</strong> — recurring monthly or annual fee. Works for SaaS, content, tools. High LTV but harder to sell upfront in low-trust markets.</li><li><strong>Freemium</strong> — free basic tier, paid advanced features. Works when the free tier creates enough value to attract users who convert to paid. Requires very large user base to work economically.</li><li><strong>Usage-based</strong> — charge per use. Works for infrastructure, APIs, communications. Easy to start, scales smoothly.</li><li><strong>Marketplace commission</strong> — take a cut of transactions between buyers and sellers. Works when you aggregate supply and demand. Network effects make this powerful when it works.</li><li><strong>Direct sales</strong> — sell directly to businesses (B2B). Longer sales cycle but higher contract values. Works in Nigeria for HR, ERP, compliance tools.</li></ul>"),
            ("Pricing Strategy and Psychology", 12, "<h2>Price Is a Strategic Tool, Not a Maths Problem</h2><p>Most founders price their product by calculating their costs and adding a margin. This is cost-plus pricing — and it is almost always wrong for an early-stage startup.</p><p>The right starting point for pricing is: <em>how much value does this create for the customer?</em> A software that saves a business ₦500,000/month in payroll errors is worth far more than the cost to build it.</p><h3>Three Pricing Strategies</h3><ol><li><strong>Value-based pricing</strong> — charge based on the value you create. Best for B2B where value is quantifiable. Hardest to implement but most profitable.</li><li><strong>Competitive pricing</strong> — price relative to alternatives. Easier but creates a race to the bottom if everyone follows it.</li><li><strong>Penetration pricing</strong> — start low to acquire users, raise later. Works when retention is high and switching costs increase over time. Dangerous if you can't survive the initial low-price period.</li></ol><h3>Psychological Pricing Principles</h3><ul><li>Anchoring: always show a higher price before showing your price</li><li>The middle option: most customers choose the middle of three options</li><li>Annual discounts: offer 15–20% off for annual payment — this improves cash flow dramatically</li></ul>"),
            ("Unit Economics Basics", 12, "<h2>The Three Numbers That Tell You If Your Business Works</h2><p><strong>Customer Acquisition Cost (CAC)</strong> — total money spent on sales and marketing divided by number of customers acquired. If you spent ₦500,000 on ads and got 50 customers, your CAC is ₦10,000.</p><p><strong>Lifetime Value (LTV)</strong> — total revenue you expect from one customer over their full relationship with you. Monthly Revenue × Average Customer Lifespan (months). If a customer pays ₦5,000/month and stays 12 months, LTV is ₦60,000.</p><p><strong>LTV:CAC Ratio</strong> — the single most important ratio in your business. Industry standard is 3:1 (LTV should be at least 3× CAC). In the example above: LTV ₦60,000 / CAC ₦10,000 = 6:1. Excellent.</p><h3>The Payback Period</h3><p>How many months does it take to recoup the cost of acquiring a customer? CAC ÷ Monthly Revenue per customer. If CAC is ₦10,000 and monthly revenue is ₦5,000, payback is 2 months. That's healthy. If payback is 18+ months, you have a cash flow problem even if your LTV:CAC looks good.</p>")
        ],
        "exercise_title": "Business Model Canvas",
        "exercise_instructions": "<p>Complete a full Business Model Canvas for your startup idea.</p><ol><li>Download or draw the Business Model Canvas template (9 boxes)</li><li>Fill in each box based on your research from Weeks 2–5</li><li>Identify the box you're most uncertain about — that's your next validation priority</li><li>Write a 3-sentence summary of your business model: who you serve, how you create value, and how you make money</li></ol>",
        "exercise_tips": "<p>It's fine to have blanks and question marks in your canvas — that's honest. What's not fine is filling in boxes with guesses you haven't validated. Mark unvalidated assumptions clearly.</p>",
        "deliverable_title": "Business Model Canvas + Revenue Rationale",
        "deliverable_desc": "<p>Submit:</p><ol><li>Your completed Business Model Canvas (photo or digital version)</li><li>A 3-sentence description of your revenue model and why it fits your market and customer</li><li>Your initial pricing (even if provisional): what you plan to charge, and one sentence on how you arrived at that number</li><li>Initial unit economics estimate: estimated CAC, LTV, and LTV:CAC ratio (rough numbers are fine at this stage)</li></ol>",
        "deliverable_format": "Canvas image + 1-page document",
    },
    {
        "week": 7,
        "title": "Brand Identity & Positioning",
        "overview": "<p>Your brand is the story people tell about you when you're not in the room. For a startup, brand is not a logo — it's the sum of every impression you create. This week you'll learn to build a brand foundation that resonates with your target customer, differentiates you from competitors, and gives your startup a voice that is distinctly yours.</p>",
        "objectives": "<ul><li>Understand what brand really means for an early-stage startup</li><li>Apply naming frameworks to generate and evaluate name options</li><li>Write a clear positioning statement</li><li>Develop 3 brand values and a tone-of-voice guide</li></ul>",
        "lessons": [
            ("What Brand Really Means for a Startup", 8, "<h2>Brand Is Not Your Logo</h2><p>Most early-stage founders think about brand too late (once they have traction) or too early (before they understand their customer). The right time is now — after you understand your customer and your market, but before you start acquiring users at scale.</p><p>Brand is the set of associations people have with your company. It's what they feel when they hear your name. It's what they say to a friend when recommending you. It's what they post online when they're happy or angry.</p><h3>Why Brand Matters Earlier Than You Think</h3><ul><li>Brand determines who feels your product is \"for them\" — and the wrong signal repels your best customers</li><li>Brand affects pricing power — people pay more for brands they trust</li><li>Brand determines who wants to work for you — and at what salary</li><li>Brand is one of the few defensible advantages a startup has against a well-funded competitor</li></ul>"),
            ("Naming Your Business — Frameworks and Rules", 15, "<h2>The Name Is a First Impression That Never Goes Away</h2><p>A great name is memorable, easy to spell and pronounce, available as a domain and social handle, and signals something about what you do or who you are. You don't need all of these — but you want as many as possible.</p><h3>The Five Types of Names</h3><ol><li><strong>Descriptive</strong> — directly describes what you do. Easy to understand, hard to differentiate. (Nigeria Post, AccessBank)</li><li><strong>Suggestive</strong> — evokes a quality or benefit. (Flutterwave — smooth money flow. Paystack — a stack of payment options)</li><li><strong>Abstract</strong> — no direct meaning, creates a blank canvas for brand-building. (Google, Uber, Apple)</li><li><strong>Acronym/Invented</strong> — shortened or created words. (GUO, GTBank)</li><li><strong>Founder name</strong> — the founder as the brand. Works for some industries (consulting, law, fashion). Hard to sell or transfer later.</li></ol><h3>The Naming Checklist</h3><ul><li>Can you say it on the phone without spelling it?</li><li>Is the .com (or .ng) domain available?</li><li>Does it mean something offensive in any major language?</li><li>Is it already trademarked in your industry?</li><li>Does it sound like something your customers already trust?</li></ul>"),
            ("Crafting a Positioning Statement", 10, "<h2>One Sentence That Contains Your Entire Strategy</h2><p>A positioning statement is an internal document — not a tagline, not a mission statement. It's a precise description of who you serve, what you offer, how you're different, and why that difference matters. It guides every brand and marketing decision.</p><p>The template: <em>For [target customer] who [has this problem/need], [Company name] is the [category] that [key benefit]. Unlike [competitors], we [key difference].</em></p><p>Example for a logistics startup:</p><blockquote>For Lagos small business owners who lose revenue due to unreliable last-mile delivery, SwiftMove is the logistics platform that guarantees same-day delivery with real-time tracking. Unlike traditional courier services, we offer a delivery guarantee or your money back.</blockquote><p>Everything in your positioning should be defensible: you should be able to explain why your target customer cares about each claim.</p>"),
            ("Differentiation — Being Different vs. Being Better", 8, "<h2>Better Is Not a Strategy</h2><p>\"We're better than X\" is not a positioning. Better is temporary — someone can always build faster, cheaper, or add more features. Different is structural — it's harder to copy because it usually requires a different business model, a different customer relationship, or a different set of values.</p><h3>Types of Differentiation That Last</h3><ul><li><strong>Customer focus</strong> — you serve a specific underserved segment with excellence. (Kuda Bank — digital-native Nigerians underserved by traditional banks)</li><li><strong>Business model</strong> — you've structured your economics differently, allowing you to offer something others can't profitably match</li><li><strong>Distribution</strong> — you reach customers through a channel others haven't figured out or don't want to invest in</li><li><strong>Community and trust</strong> — especially in markets where trust is the barrier, being the most trusted provider is a durable moat</li></ul>")
        ],
        "exercise_title": "Name Generation and Evaluation",
        "exercise_instructions": "<p>This week's exercise focuses on naming:</p><ol><li>Generate 10 name candidates for your startup. Use at least 2 from each category: descriptive, suggestive, and abstract</li><li>Apply the naming checklist to each of your top 5 names</li><li>Check domain and social handle availability for your top 3</li><li>Choose your preferred name and write a 2-sentence explanation of why it works for your brand</li></ol>",
        "exercise_tips": "<p>Don't fall in love with a name too quickly. Run your top 3 past 5 people from your target segment and ask only: \"What does this name make you think of?\" Their answers will surprise you.</p>",
        "deliverable_title": "Brand Brief",
        "deliverable_desc": "<p>Submit a Brand Brief containing:</p><ol><li><strong>Name:</strong> Your chosen startup name and the rationale</li><li><strong>Tagline:</strong> A 3–7 word tagline that captures your core value proposition</li><li><strong>Positioning Statement:</strong> Written using the template from Lesson 3</li><li><strong>3 Brand Values:</strong> Three words and a paragraph explaining each</li><li><strong>Tone of Voice:</strong> 4 adjectives that describe how your brand should sound in writing and speech. Include one sentence example of your brand tone and one sentence that shows the tone you want to avoid.</li></ol>",
        "deliverable_format": "1–2 page document or branded one-pager",
    },
    {
        "week": 8,
        "title": "Go-to-Market Strategy",
        "overview": "<p>You've built something. Now what? How do you get your first 100 customers? This is the question that separates startups that grow from startups that stagnate. Your go-to-market strategy is not a marketing plan — it's a systematic approach to acquiring and retaining your first cohort of customers, learning from them, and building a repeatable engine.</p>",
        "objectives": "<ul><li>Understand the three growth motions and which fits your business</li><li>Identify your top 3 customer acquisition channels</li><li>Design a path to your first 100 customers</li><li>Build a set of growth experiments to run in the next 4 weeks</li></ul>",
        "lessons": [
            ("The GTM Framework", 10, "<h2>What Go-to-Market Really Means</h2><p>GTM is the plan you execute to bring a product to market and acquire customers. A strong GTM strategy answers four questions:</p><ol><li>Who are we selling to first? (ICP — Ideal Customer Profile)</li><li>How will we reach them? (Channels)</li><li>What will we say to them? (Messaging)</li><li>How will we turn interest into purchase? (Sales motion)</li></ol><p>Every decision in your GTM should flow from your ICP — the most specific definition of the customer most likely to buy, benefit from, and advocate for your product in the early stages.</p><h3>The ICP vs. the Persona</h3><p>Your customer persona is a broad description of your target market. Your ICP is even more specific — it's the subset of that persona who is most ready to buy right now. For a B2B startup, ICP includes company size, industry, budget authority, and trigger events (what makes them look for a solution now?).</p>"),
            ("Sales-Led vs. Marketing-Led vs. Product-Led Growth", 12, "<h2>Three Ways to Grow a Business</h2><p><strong>Sales-Led Growth (SLG)</strong> — salespeople drive acquisition. Works for high-ticket B2B sales where the deal value justifies human interaction. The customer's buying decision is primarily influenced by a salesperson. Best for: enterprise software, financial services, complex B2B tools.</p><p><strong>Marketing-Led Growth (MLG)</strong> — content, advertising, and brand drive acquisition. Works when your customer does significant research before buying. The customer's journey starts with awareness, not a sales call. Best for: e-commerce, consumer apps, SME tools.</p><p><strong>Product-Led Growth (PLG)</strong> — the product itself drives acquisition and expansion. Users discover the product (often free), experience value, and either upgrade or invite others. Best for: SaaS tools with network effects, developer tools, collaboration software (Slack, Notion, Figma).</p><h3>Which One for an Early-Stage Nigerian Startup?</h3><p>Most early-stage Nigerian startups should start with sales-led growth — even if the long-term model is PLG or MLG. The reason: sales conversations generate the fastest and richest feedback. Before you invest in content or product virality, go sell to 20 people manually and learn from every conversation.</p>"),
            ("Channel Selection for African Markets", 15, "<h2>Where Your Customers Actually Are</h2><p>Channel strategy in Nigeria is different from Silicon Valley playbooks. Here are the channels that work:</p><ul><li><strong>WhatsApp</strong> — the most powerful distribution channel in Nigeria for consumer and SME products. Groups, broadcast lists, and word of mouth via WhatsApp are often more effective than Facebook ads.</li><li><strong>Physical presence</strong> — market activations, in-person demos, door-to-door sales. Still very effective for products targeting SMEs, markets, or areas with lower internet penetration.</li><li><strong>Trusted intermediaries</strong> — agents, market leaders, association heads. If you can get the leader of a traders' association to endorse your product, you unlock access to hundreds of customers at once.</li><li><strong>Social media (Instagram, TikTok, LinkedIn)</strong> — effective for brand building and content marketing. Instagram for B2C, LinkedIn for B2B, TikTok for young consumer audiences.</li><li><strong>Referral programmes</strong> — incentivised word-of-mouth. Opay, Piggyvest, and others scaled rapidly through referral rewards. Works when the product has clear value and the incentive is meaningful.</li><li><strong>Partnerships</strong> — integration with or distribution through established platforms (banks, telcos, trade associations)</li></ul>"),
            ("Getting Your First 10 Customers", 8, "<h2>Do Things That Don't Scale</h2><p>Paul Graham's famous essay \"Do Things That Don't Scale\" is one of the most important pieces of startup writing. The insight: in the early days, focus on doing things manually that will eventually be automated. Go find your first 10 customers personally. Don't wait for them to find you.</p><h3>Tactics for Your First 10</h3><ul><li>Go where your customers are — literally. If they're in Alaba Market, go to Alaba. If they're in tech communities, join every Slack group and attend every meetup.</li><li>Use your existing network. Who do you already know who fits your ICP? Start there.</li><li>Ask for warm introductions. \"Do you know anyone who [experiences the problem]?\" is a question you should be asking everyone you meet.</li><li>Make it personal. Send individualised messages, not mass emails. \"I noticed you posted about X\" converts far better than \"Dear Sir/Madam.\"</li><li>Offer a deal that feels too good. Your first customers are taking a risk on you. Make it worth their while: free first month, personal onboarding, direct access to the founder.</li></ul>")
        ],
        "exercise_title": "GTM Channel Map and Experiments",
        "exercise_instructions": "<p>This exercise results in a concrete action plan for acquiring your first customers.</p><ol><li>Revisit your ICP (from Week 4 personas). Write the most specific version possible.</li><li>List your top 5 potential acquisition channels. Rate each: reach (how many of your ICP can you access?), cost (₦ to reach 100 people), conversion likelihood (high/medium/low)</li><li>Select your top 3 channels</li><li>For each channel, design one experiment: what will you test, with how many people, over how many days, and what metric will tell you if it worked?</li><li>Set a target: how many customers will you aim to acquire in the next 4 weeks?</li></ol>",
        "exercise_tips": "<p>Don't try to do all channels at once. Pick one and go deep before adding the next. Diluted effort across 5 channels produces worse results than concentrated effort on 1.</p>",
        "deliverable_title": "Go-to-Market Plan",
        "deliverable_desc": "<p>A 1–2 page GTM Plan containing:</p><ol><li><strong>ICP Definition:</strong> Your most specific Ideal Customer Profile (one paragraph)</li><li><strong>Top 3 Channels:</strong> Why you chose each, how you'll use it, and your 4-week target</li><li><strong>Path to First 100 Customers:</strong> A step-by-step narrative of how you will acquire your first 100 customers — including specific tactics, who you'll reach out to first, and what you'll say</li><li><strong>Success Metrics:</strong> 3 specific metrics that will tell you your GTM is working (not just \"number of signups\")</li></ol>",
        "deliverable_format": "1–2 page document",
    },
    {
        "week": 9,
        "title": "Product Development Basics",
        "overview": "<p>You don't need to be a developer to build a product. But you do need to understand how products are built well enough to lead a technical team, work with a co-founder, or commission work from freelancers. This week is about the fundamentals: how to write product specs, use no-code tools, and manage your early product development without a technical background.</p>",
        "objectives": "<ul><li>Write clear user stories and acceptance criteria</li><li>Understand basic Agile/Lean product development methodology</li><li>Identify no-code and low-code tools relevant to your idea</li><li>Produce a Product Requirements Document (PRD) for your MVP</li></ul>",
        "lessons": [
            ("Working with Developers — What They Need From You", 10, "<h2>The Founder-Developer Relationship</h2><p>The most common breakdown between non-technical founders and developers is not a technical problem — it's a communication problem. Developers can build almost anything. What breaks projects is unclear requirements, scope creep, and changing priorities mid-build.</p><h3>What Good Requirements Look Like</h3><p>A developer needs to know: what the user will see, what the user will do, what the system should do in response, and what \"done\" looks like. If you can answer these four questions for every feature, you will save weeks of rework.</p><h3>Red Flags When Working with Developers</h3><ul><li>\"Just build it, we'll figure out the details as we go\" — this always costs more time than writing specs upfront</li><li>\"Can we add just one more thing?\" — scope creep is the #1 cause of delayed launches</li><li>Not having a staging/test environment before pushing to production</li><li>No version control (GitHub/GitLab) — if there's no version control, you can lose everything</li></ul>"),
            ("Writing User Stories and Acceptance Criteria", 12, "<h2>The Language of Product Development</h2><p>A user story is a simple description of a feature from the perspective of the person who will use it. It follows this format:</p><p><em>As a [type of user], I want to [perform some action] so that [I can achieve some goal].</em></p><p>Examples:</p><ul><li>As a small business owner, I want to receive a payment notification via SMS so that I know when a customer has paid without checking my phone constantly.</li><li>As a rider, I want to see the driver's location on a map in real-time so that I know when to come outside.</li></ul><h3>Acceptance Criteria</h3><p>For each user story, define acceptance criteria — the specific conditions that must be true for the story to be considered complete. Use the format:</p><p><em>Given [context], when [action], then [outcome].</em></p><p>Example: Given a customer has made a payment, when the payment is confirmed, then the seller receives an SMS with the amount and customer name within 30 seconds.</p><p>This level of specificity eliminates 80% of developer-founder disputes.</p>"),
            ("No-Code and Low-Code Tools for Nigerian Founders", 12, "<h2>Build Without Hiring a Developer</h2><p>The no-code revolution means many startups can launch without any custom code. Here are the most relevant tools for Nigerian founders:</p><ul><li><strong>Bubble.io</strong> — full web applications without code. Databases, user auth, complex logic. Best for MVPs of SaaS products, marketplaces, and portals.</li><li><strong>Flutterwave/Paystack + Webflow</strong> — build a professional e-commerce or service business website with integrated payments in days</li><li><strong>Glide</strong> — turn Google Sheets into mobile apps. Excellent for internal tools and simple consumer apps.</li><li><strong>Typeform or Tally</strong> — sophisticated forms that can automate workflows. Useful for intake processes, onboarding, surveys</li><li><strong>Notion + Make (Integromat)</strong> — powerful workflow automation for business operations without code</li><li><strong>WhatsApp Business API + Twilio</strong> — automated messaging workflows. Very powerful for Nigerian businesses where WhatsApp is primary communication</li></ul><p><strong>Rule of thumb:</strong> if you need to validate your concept and get your first 10 customers, use no-code. If you need scale and customisation, hire a developer. Don't hire a developer to build something you haven't validated.</p>"),
            ("Agile Basics — Sprints, Backlogs, and Prioritisation", 8, "<h2>How Modern Startups Build Products</h2><p>Agile methodology is not just for big companies. Its core principles — short iterations, regular feedback, and adaptability — are exactly what early-stage startups need.</p><h3>Key Agile Concepts for Founders</h3><ul><li><strong>Sprint</strong> — a fixed time period (usually 1–2 weeks) in which the team builds a specific set of features. At the end of a sprint, you should have something you can test or ship.</li><li><strong>Product Backlog</strong> — the full list of everything you want to build, in priority order. Everything goes on the backlog. Not everything gets built.</li><li><strong>Prioritisation — MoSCoW method:</strong> Must have (MVP can't function without it), Should have (important but not critical for launch), Could have (nice to have), Won't have (out of scope for now)</li><li><strong>Definition of Done</strong> — agree upfront on what \"finished\" means for every task. Does it mean coded? Tested? Deployed? Reviewed?</li></ul>")
        ],
        "exercise_title": "Write 3 User Stories with Acceptance Criteria",
        "exercise_instructions": "<p>Choose 3 core features of your MVP. For each one:</p><ol><li>Write one user story in the standard format</li><li>Write 3 acceptance criteria in the Given/When/Then format</li><li>Rate the feature using MoSCoW (Must/Should/Could/Won't)</li></ol><p>You should end up with 3 user stories, 9 acceptance criteria, and 3 MoSCoW ratings.</p>",
        "exercise_tips": "<p>Test your user stories on a developer or technical friend. If they can read it and immediately understand what to build, you've written it well. If they ask clarifying questions, those questions are gaps in your spec.</p>",
        "deliverable_title": "Product Requirements Document (PRD)",
        "deliverable_desc": "<p>Write a PRD for your MVP containing:</p><ol><li><strong>Problem Recap:</strong> One paragraph re-stating the problem you're solving (from your Week 2 deliverable)</li><li><strong>User Stories:</strong> 5 user stories (from your Week 5 MVP Feature List + this week's exercise), each with acceptance criteria</li><li><strong>MVP Scope:</strong> A clear list of what IS included in the MVP</li><li><strong>Out of Scope:</strong> A list of what is NOT in the MVP and why</li><li><strong>Success Metrics:</strong> How will you measure if the MVP is working? (3 metrics)</li><li><strong>Technical Notes:</strong> Any known technical constraints or dependencies</li></ol>",
        "deliverable_format": "2–3 page document",
    },
    {
        "week": 10,
        "title": "Finance for Founders",
        "overview": "<p>You don't need an accounting degree. You need to understand your numbers well enough to make good decisions, catch problems early, and talk confidently to investors. This week covers the financial fundamentals every founder must have: cash flow, pricing, break-even, and the basics of startup fundraising.</p>",
        "objectives": "<ul><li>Read and build a basic Profit & Loss statement</li><li>Understand cash flow and why it kills more startups than competition does</li><li>Calculate your break-even point</li><li>Understand the difference between equity, debt, and grant funding</li></ul>",
        "lessons": [
            ("Reading and Building a Basic P&L", 15, "<h2>The Profit and Loss Statement</h2><p>A Profit & Loss (P&L) statement, also called an income statement, shows how much money came in, how much went out, and whether the business made a profit over a specific period.</p><p>The structure:</p><ul><li><strong>Revenue</strong> — all money earned from your product or service</li><li><strong>Cost of Goods Sold (COGS)</strong> — direct costs of delivering your product (materials, delivery, server costs for SaaS)</li><li><strong>Gross Profit</strong> = Revenue − COGS</li><li><strong>Operating Expenses</strong> — salaries, rent, marketing, tools, insurance</li><li><strong>Operating Profit (EBITDA)</strong> = Gross Profit − Operating Expenses</li><li><strong>Tax and interest</strong></li><li><strong>Net Profit</strong> = what's actually left</li></ul><h3>The Most Important Ratio: Gross Margin</h3><p>Gross Margin = (Gross Profit / Revenue) × 100. A SaaS product typically has 70–90% gross margin. A logistics company might have 15–25%. Your gross margin determines how much money is available to invest in growth after delivering your product.</p>"),
            ("Cash Flow — the Thing That Actually Kills Startups", 12, "<h2>Profitable Businesses Die of Cash Flow Problems</h2><p>This is one of the most counterintuitive facts in business: a company can be profitable on paper and still run out of cash and close. This happens when revenue is collected later than expenses are paid.</p><p>Example: You sign a ₦10M contract. The client pays in 90 days. But you need to pay salaries and suppliers now. If you don't have the cash to cover the 90-day gap, you can't operate — even though you have a ₦10M receivable.</p><h3>The Cash Flow Statement</h3><p>Unlike the P&L (which shows revenue when it's earned), the cash flow statement shows money when it actually moves. It has three sections:</p><ul><li><strong>Operating cash flow</strong> — cash from daily operations. The most important number.</li><li><strong>Investing cash flow</strong> — money spent on assets or infrastructure</li><li><strong>Financing cash flow</strong> — money from investors or loans</li></ul><h3>The 13-Week Cash Flow Forecast</h3><p>Every founder should maintain a 13-week (3-month) rolling cash flow forecast. It's a simple spreadsheet: expected cash in vs. cash out, week by week. If any week goes negative, you know about it 3 months in advance and can act.</p>"),
            ("Break-Even Analysis", 8, "<h2>When Does Your Business Stop Losing Money?</h2><p>Your break-even point is the number of units sold (or revenue earned) at which your total revenue equals your total costs. Above break-even, you make a profit. Below it, you make a loss.</p><p>Formula: Break-Even Units = Fixed Costs ÷ (Price per Unit − Variable Cost per Unit)</p><p>Example: Fixed costs ₦500,000/month (rent, salaries, tools). Price ₦25,000. Variable cost per unit ₦5,000. Break-Even = ₦500,000 ÷ (₦25,000 − ₦5,000) = 25 units per month.</p><p>Knowing your break-even tells you: how many customers you need before the business sustains itself, whether your pricing is viable, and how sensitive your profitability is to cost changes.</p>"),
            ("Fundraising Basics", 10, "<h2>Types of Startup Funding</h2><p><strong>Grants</strong> — free money from government bodies, development organisations, or competitions. No dilution. Limited supply. Usually comes with reporting requirements. Best for: early validation, research-oriented startups, social enterprises. Examples: NITDA, GSMA grants, Google for Startups, Tony Elumelu Foundation.</p><p><strong>Equity (Angel/VC)</strong> — investors give money in exchange for a percentage of your company. No repayment. Investors win only if your company grows significantly. Best for: high-growth potential startups, businesses with large addressable markets.</p><p><strong>Debt</strong> — loans from banks, development finance institutions, or revenue-based financing. You keep equity but must repay. Best for: businesses with predictable revenue and assets, expansion capital for profitable businesses.</p><p><strong>Revenue-Based Financing</strong> — a lender gives you money in exchange for a percentage of future revenue until a set amount is repaid. Emerging in Nigeria (Carbon, Brass). Best for: businesses with recurring revenue and strong unit economics.</p><h3>The Right Order</h3><p>The smartest sequence: grants/competitions → friends and family → angels → institutional VC. Each step requires more proof than the last. Don't try to raise VC funding before you've proven the model at small scale.</p>")
        ],
        "exercise_title": "6-Month Financial Model",
        "exercise_instructions": "<p>Build a simple 6-month financial projection for your startup using a spreadsheet.</p><ol><li>List all your monthly expenses (fixed and variable)</li><li>Project your monthly revenue based on your pricing and customer acquisition plan from Week 8</li><li>Calculate monthly gross profit, operating profit, and cash balance</li><li>Calculate your break-even point</li><li>Identify which month (if any) you run out of cash — this is your \"burn runway\"</li></ol>",
        "exercise_tips": "<p>Be conservative on revenue and honest about costs. A model that shows you running out of cash in Month 4 is more useful than an optimistic model that makes you feel comfortable but leads to a real cash crisis.</p>",
        "deliverable_title": "6-Month Financial Projection",
        "deliverable_desc": "<p>Submit your 6-month financial model including:</p><ol><li>Monthly revenue projection (with assumptions clearly stated)</li><li>Monthly expense breakdown (fixed + variable)</li><li>Monthly gross profit and operating profit</li><li>Running cash balance</li><li>Break-even month</li><li>One paragraph identifying your biggest financial risk and how you plan to manage it</li></ol>",
        "deliverable_format": "Google Sheets or Excel spreadsheet + 1 paragraph",
    },
    {
        "week": 11,
        "title": "Pitching & Storytelling",
        "overview": "<p>Investors don't buy spreadsheets. They buy stories. A compelling narrative that makes an investor feel the problem, believe in your solution, and trust your team will open more doors than a perfect financial model. This week you'll build your pitch from the ground up — learning the structure that works, the mistakes Nigerian founders typically make, and how to handle tough questions in the room.</p>",
        "objectives": "<ul><li>Structure a compelling 10-slide pitch deck</li><li>Understand the narrative arc of a great startup story</li><li>Avoid the 5 most common pitch mistakes</li><li>Prepare confident answers to the 10 questions investors always ask</li></ul>",
        "lessons": [
            ("The Anatomy of a Great Startup Story", 10, "<h2>Every Successful Pitch Follows a Story Structure</h2><p>The best pitch decks are not collections of data slides. They follow a narrative arc that takes the investor through a specific emotional and intellectual journey:</p><ol><li><strong>The world as it is:</strong> Set the scene. Who is your customer and what does their life look like today?</li><li><strong>Something is wrong:</strong> Introduce the problem. Make it tangible and painful — use a specific example, a real statistic, or a quote from a real person.</li><li><strong>There must be a better way:</strong> Establish that this problem is worth solving — the size of the opportunity, the current inadequacy of solutions.</li><li><strong>Introducing the hero:</strong> Enter your startup. What is your solution? Show (don't just tell) how it works.</li><li><strong>The proof:</strong> Evidence that people want this and that you can execute. Traction, team, validation.</li><li><strong>The call to action:</strong> What you're asking for and what you'll do with it.</li></ol><p>This is the story structure of every great pitch — from Airbnb's first investor deck to Flutterwave's Series A.</p>"),
            ("The 10-Slide Pitch Deck Framework", 15, "<h2>The Sequoia Framework (With Nigerian Adaptations)</h2><p>Sequoia Capital's pitch deck structure is the most widely used in the world. Here it is with adaptations for the Nigerian context:</p><ol><li><strong>Cover:</strong> Company name, tagline, founder name, date. Simple and clean.</li><li><strong>Problem:</strong> The pain you're solving. One slide. Use a specific story or statistic. Not a bullet list.</li><li><strong>Solution:</strong> What you've built. One paragraph. One screenshot or visual. No more.</li><li><strong>Market Size:</strong> Your TAM/SAM/SOM from Week 3. Bottom-up numbers. Show you understand the Nigerian market specifically.</li><li><strong>Business Model:</strong> How you make money. One clear diagram or table.</li><li><strong>Traction:</strong> Your most compelling metric. Even early traction matters — 50 paying customers and 40% month-on-month growth tells a better story than aspirational projections.</li><li><strong>Go-to-Market:</strong> How you'll acquire customers at scale. Channel strategy and early wins.</li><li><strong>Competition:</strong> Your competitive matrix. Show your differentiated position.</li><li><strong>Team:</strong> Why you? Focus on unfair advantages — domain expertise, relevant experience, network. Investors bet on teams.</li><li><strong>The Ask:</strong> How much you're raising, what you'll use it for (3–4 line items), and key milestones you'll hit with the funding.</li></ol>"),
            ("Common Pitch Mistakes Nigerian Founders Make", 10, "<h2>What Investors See Too Often</h2><ol><li><strong>Overstating market size.</strong> \"We are targeting the African market which is worth $600 billion.\" Investors see through this. Use a credible SAM with explained assumptions.</li><li><strong>No traction and no acknowledgement of it.</strong> If you have no customers, say so — and explain exactly why and what you've done to validate the idea instead.</li><li><strong>Refusing to name competitors.</strong> \"We have no competition\" always damages credibility. You have competition. Name them. Show why you're different.</li><li><strong>Too many features, not enough story.</strong> 6 slides of feature descriptions and no emotional arc. Investors don't care about features. They care about outcomes.</li><li><strong>Asking for too little or too little specificity on use of funds.</strong> \"We need ₦50M\" with no breakdown. Show exactly: ₦20M for tech team, ₦15M for 6 months' marketing, ₦15M for operations. Specificity signals seriousness.</li></ol>"),
            ("Handling Tough Questions in the Room", 8, "<h2>The 10 Questions Every Investor Asks</h2><p>Prepare a confident, honest answer to each of these:</p><ol><li>Why are you the right person to build this?</li><li>What happens if [major competitor] decides to build this?</li><li>What have you learned from talking to customers?</li><li>Why now? Why hasn't this been built already?</li><li>What does success look like in 3 years?</li><li>What's your customer acquisition cost and how do you plan to bring it down?</li><li>What will you do differently if this doesn't work?</li><li>Tell me about a time this product failed or a customer churned.</li><li>What do you need beyond money?</li><li>What keeps you up at night about this business?</li></ol><p>The worst answers are defensive. The best answers are honest, reflective, and show you've thought deeply about the risks. An investor who hears \"that's a risk I've been thinking hard about, and here's how we're managing it\" is far more impressed than one who hears \"that won't happen to us.\"</p>")
        ],
        "exercise_title": "Draft Your 10-Slide Pitch Deck",
        "exercise_instructions": "<p>Build your first full pitch deck this week.</p><ol><li>Use the 10-slide framework from Lesson 2</li><li>Each slide should have: a headline (the point of the slide, not a label), a visual or data point, and no more than 3 bullet points</li><li>The entire deck should be readable in 4 minutes without the presenter speaking</li><li>Share it with one person outside your startup — a mentor, a friend in business. Ask: what questions does this deck NOT answer?</li></ol>",
        "exercise_tips": "<p>Use Google Slides or Canva for simplicity. Good design matters but don't let perfecting the design prevent you from finishing the content. A clear story in plain slides beats a confusing story in beautiful ones.</p>",
        "deliverable_title": "Full Pitch Deck",
        "deliverable_desc": "<p>Submit your complete 10–12 slide pitch deck covering:</p><ol><li>Cover slide</li><li>Problem (with a specific story or data point)</li><li>Solution</li><li>Market size (bottom-up)</li><li>Business model</li><li>Traction (or validation if pre-revenue)</li><li>Go-to-market strategy</li><li>Competitive landscape</li><li>Team</li><li>The Ask (amount, use of funds, milestones)</li></ol>",
        "deliverable_format": "PDF slide deck (10–12 slides, max 5MB)",
    },
    {
        "week": 12,
        "title": "Demo Day and What's Next",
        "overview": "<p>You've covered the full arc — from founder mindset to pitch deck. This final week is about Demo Day: how to present your 5-minute pitch under pressure, how to follow up with investors and partners afterward, and how to build a 90-day roadmap for the most important quarter of your startup's life. The program ends. The work accelerates.</p>",
        "objectives": "<ul><li>Structure and rehearse a compelling 5-minute Demo Day pitch</li><li>Build a post-Demo Day investor follow-up playbook</li><li>Create a realistic 90-day roadmap</li><li>Understand how to use the LaunchPadi alumni network</li></ul>",
        "lessons": [
            ("Structuring Your 5-Minute Demo Day Pitch", 12, "<h2>Five Minutes is Both Too Short and Long Enough</h2><p>A Demo Day pitch is not a pitch deck walkthrough. It's a performance — a structured, rehearsed, confident delivery that makes the audience feel something and want to have a further conversation. The goal is not to close an investment on stage. The goal is to get the meeting after.</p><h3>The 5-Minute Structure (Suggested Timing)</h3><ul><li><strong>0:00–0:30 — The Hook:</strong> One sentence that makes the audience lean forward. Either a striking statistic, a personal story, or a question. \"Every day, 2,000 Lagos businesses lose a customer because their delivery was late. We're fixing that.\"</li><li><strong>0:30–1:30 — The Problem:</strong> Make it tangible. One specific story if possible. Establish the market size in one sentence.</li><li><strong>1:30–2:30 — The Solution + Demo:</strong> Show your product, not slides about your product. A 30-second live demo or screen recording is worth 5 feature slides.</li><li><strong>2:30–3:30 — Traction + Business Model:</strong> Your most compelling metric. One sentence on how you make money.</li><li><strong>3:30–4:30 — Team:</strong> Why you? One sentence each on the key team members' relevant experience.</li><li><strong>4:30–5:00 — The Ask:</strong> Amount. Key milestones you'll hit. Finish strong.</li></ul>"),
            ("The Post-Demo Follow-Up Playbook", 10, "<h2>The Money Is in the Follow-Up</h2><p>Most investment decisions are not made during Demo Day. They're made in the meetings and calls that follow — and most founders squander the momentum by failing to follow up systematically.</p><h3>The 48-Hour Rule</h3><p>Within 48 hours of Demo Day, send a personalised email to every investor who expressed interest. Not a mass email — a specific, personalised note that references the conversation you had. Attach your pitch deck. Include a clear next step.</p><h3>The Follow-Up Template</h3><p>Subject: [Your Company] — following up from LaunchPadi Demo Day</p><blockquote>Hi [Name], Thank you for taking the time to speak with me at Demo Day. As we discussed, [one sentence reference to specific conversation point]. I've attached our pitch deck and would love to schedule a 30-minute call to go deeper on [the specific thing they seemed most interested in]. Would [two specific time options] work for you?<br>Best, [Name]</blockquote><h3>After the Call</h3><ul><li>Send a follow-up email the same day summarising what was discussed and agreed</li><li>If they asked for a document, send it within 24 hours</li><li>Keep a simple CRM (even a Google Sheet) of every investor, their status, and the last action taken</li></ul>"),
            ("Building Your 90-Day Roadmap", 12, "<h2>The Most Important Quarter of Your Startup's Life</h2><p>The 90 days after Demo Day are critical. You have momentum, a pitch deck, a network, and — ideally — some investor interest. How you use this window determines whether your startup accelerates or stalls.</p><h3>The 90-Day Framework</h3><p>Organise your roadmap around three questions:</p><ol><li><strong>What are the 3 things that, if achieved, would make the next 90 days a success?</strong> Be specific: \"Sign 10 paying customers\", \"Close a ₦5M seed round\", \"Launch the Android app\". Not \"grow the business.\"</li><li><strong>What resources do I need that I don't currently have?</strong> People, capital, tools, partnerships, introductions</li><li><strong>What is the most likely thing to go wrong and how will I respond?</strong> Pre-mortems are more useful than optimistic plans</li></ol><h3>Weekly Cadence</h3><p>Every Monday morning: review last week's goals vs. actual. Set this week's top 3 priorities. Every Friday: what did you ship, what did you learn, what do you need?</p>"),
            ("Using the LaunchPadi Alumni Network", 5, "<h2>Your Network is One of Your Most Valuable Assets</h2><p>The LaunchPadi alumni network is a community of founders who have been through the same program, face the same challenges, and are building in the same ecosystem. This network is one of the most underused assets most alumni have.</p><h3>How to Use the Network Well</h3><ul><li><strong>Give before you take.</strong> Share introductions, insights, opportunities with other founders without expecting an immediate return. The goodwill compounds.</li><li><strong>Ask specific questions, not general ones.</strong> \"Does anyone have contacts at Shoprite Nigeria?\" gets answers. \"Can anyone help me grow my business?\" does not.</li><li><strong>Share your wins and losses equally.</strong> The alumni who share honest updates — including failures — build more trust and get more support than those who only post success updates.</li><li><strong>Come back and give back.</strong> The most successful alumni eventually become mentors to new cohorts. The cycle is what makes the ecosystem valuable over time.</li></ul>")
        ],
        "exercise_title": "3-Minute Pitch Video",
        "exercise_instructions": "<p>Record a 3-minute pitch video presenting your startup.</p><ol><li>Use your 10-slide deck from Week 11 as a guide, but speak naturally — don't read from the slides</li><li>Record using your phone or laptop camera. A clean background, good lighting, and clear audio are the only technical requirements</li><li>Review the recording once and note 3 things to improve</li><li>Record a second version incorporating those improvements</li><li>Share the second version with your cohort group for peer feedback</li></ol>",
        "exercise_tips": "<p>Most people hate watching themselves on video. Do it anyway. The founders who review their own pitches and improve them are consistently better in live investor meetings than those who don't.</p>",
        "deliverable_title": "90-Day Post-Program Roadmap",
        "deliverable_desc": "<p>Submit a 90-day roadmap document containing:</p><ol><li><strong>Top 3 Milestones:</strong> The three things that, if achieved, would make the next 90 days a success. Be specific and measurable.</li><li><strong>Resources Needed:</strong> What do you need that you don't currently have? (People, capital, introductions, tools)</li><li><strong>Week-by-Week Plan:</strong> A week-by-week breakdown for the first 4 weeks (the most critical period)</li><li><strong>One Risk:</strong> The most likely thing to go wrong in the next 90 days, and your mitigation plan</li><li><strong>Success Definition:</strong> In one paragraph — what does a successful first 90 days look like for your startup?</li></ol>",
        "deliverable_format": "1–2 page document",
    },
]


class Command(BaseCommand):
    help = "Seed the LaunchPadi Idea-Stage Founders LMS with all 12 modules, lessons, exercises, and deliverables"

    def add_arguments(self, parser):
        parser.add_argument('--reset', action='store_true', help='Delete existing course and reseed from scratch')

    def handle(self, *args, **options):
        if options['reset']:
            LMSCourse.objects.filter(slug='launchpadi-idea-stage-program').delete()
            self.stdout.write(self.style.WARNING("Existing course deleted."))

        course, created = LMSCourse.objects.get_or_create(
            slug='launchpadi-idea-stage-program',
            defaults={
                'title': 'LaunchPadi Idea-Stage Founders Program',
                'description': '<p>The LaunchPadi Idea-Stage Program is a 12-module self-paced curriculum for Nigerian founders at the earliest stage of their entrepreneurial journey. Each module covers one week of learning: structured lessons, a practical exercise, and a concrete deliverable you will keep long after the program ends.</p><p>The program covers everything from founder mindset to Demo Day — building your knowledge, skills, and confidence to take your idea forward with clarity and conviction.</p>',
                'is_active': True,
            }
        )

        if created:
            self.stdout.write(self.style.SUCCESS(f"Created course: {course.title}"))
        else:
            self.stdout.write(self.style.WARNING(f"Course already exists: {course.title}. Updating modules..."))

        for i, module_data in enumerate(MODULES):
            module, _ = LMSModule.objects.update_or_create(
                course=course,
                week_number=module_data['week'],
                defaults={
                    'title': module_data['title'],
                    'overview': module_data['overview'],
                    'learning_objectives': module_data['objectives'],
                    'is_published': True,
                    'order': i + 1,
                }
            )

            for j, (title, minutes, content) in enumerate(module_data['lessons']):
                LMSLesson.objects.update_or_create(
                    module=module,
                    title=title,
                    defaults={
                        'content': content,
                        'estimated_minutes': minutes,
                        'order': j + 1,
                        'is_published': True,
                    }
                )

            LMSExercise.objects.update_or_create(
                module=module,
                title=module_data['exercise_title'],
                defaults={
                    'instructions': module_data['exercise_instructions'],
                    'tips': module_data.get('exercise_tips', ''),
                    'order': 1,
                }
            )

            LMSDeliverable.objects.update_or_create(
                module=module,
                defaults={
                    'title': module_data['deliverable_title'],
                    'description': module_data['deliverable_desc'],
                    'format_guidance': module_data['deliverable_format'],
                }
            )

            self.stdout.write(f"  ✓ Week {module_data['week']}: {module_data['title']} ({len(module_data['lessons'])} lessons)")

        self.stdout.write(self.style.SUCCESS(
            f"\nDone! Seeded {len(MODULES)} modules, {sum(len(m['lessons']) for m in MODULES)} lessons, "
            f"{len(MODULES)} exercises, {len(MODULES)} deliverables."
        ))
